import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { afterEach, it, expect, vi } from "vitest";
import { MapHierarchyControls } from "./MapHierarchyControls";
import { json, stubApi } from "@/test-utils";
const floor = { id: "f", building_id: "b", name: "Second floor", ordinal: 2, revision: 7 };
const site = { id: "s", name: "Site", zones: [], buildings: [{ id: "b", site_id: "s", name: "Plant", revision: 3, floors: [floor] }] };
afterEach(() => vi.unstubAllGlobals());
it("renames the selected map without resetting its ordinal and uses its exact revision", async () => {
  const handler = stubApi({ "/api/v1/maps/sites/s/floors/f": () => json(floor) });
  const fetch = vi.fn(handler);
  vi.stubGlobal("fetch", fetch);
  const saved = vi.fn();
  render(<MapHierarchyControls site={site} activeFloor={floor} disabled={false} onSaved={saved} onCreated={vi.fn()} onRemoved={vi.fn()}/>);
  fireEvent.click(screen.getByText("Manage maps"));
  expect(screen.getByLabelText("Map ordinal")).toHaveValue(2);
  fireEvent.change(screen.getByLabelText("Map name"), { target: { value: "Renamed plant" } });
  fireEvent.click(screen.getByText("Rename selected map"));
  await waitFor(() => expect(saved).toHaveBeenCalled());
  const request = fetch.mock.calls[0]![0] as Request;
  expect(request.method).toBe("PATCH");
  expect(request.headers.get("If-Match")).toBe("7");
  expect(await request.json()).toEqual({ name: "Renamed plant", ordinal: 2 });
});
it("creates independent named maps and shows revision/deletion refusal without mutation retries", async () => {
  const handler = stubApi({ "POST /api/v1/maps/sites/s/buildings/b/floors": () => json({ ...floor, id: "new" }), "DELETE /api/v1/maps/sites/s/floors/f": () => json({ message: "Map contains active placements" }, 409) });
  const fetch = vi.fn(handler);
  vi.stubGlobal("fetch", fetch);
  const created = vi.fn();
  const removed = vi.fn();
  render(<MapHierarchyControls site={site} activeFloor={floor} disabled={false} onSaved={vi.fn()} onCreated={created} onRemoved={removed}/>);
  fireEvent.click(screen.getByText("Manage maps"));
  fireEvent.change(screen.getByLabelText("Map name"), { target: { value: "Third plant" } });
  fireEvent.change(screen.getByLabelText("Map ordinal"), { target: { value: "3" } });
  fireEvent.click(screen.getByText("Create map"));
  await waitFor(() => expect(created).toHaveBeenCalledWith("new"));
  const body = await (fetch.mock.calls[0]![0] as Request).json();
  expect(body).toEqual({ name: "Third plant", ordinal: 3 });
  fireEvent.click(screen.getByText("Manage maps"));
  fireEvent.click(screen.getByText("Delete selected empty map"));
  await screen.findByText("Map contains active placements");
  expect(fetch).toHaveBeenCalledTimes(2);
  expect(removed).not.toHaveBeenCalled();
  expect(screen.getByText("Delete empty building")).toBeDisabled();
});
