// Package store holds database access. Package db is generated by sqlc from queries/*.sql
// and the migrations; run `make generate` after changing either.
package store

//go:generate go tool sqlc generate -f ../../sqlc.yaml
