// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_enroll_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAgentEnrollToken = `-- name: ConsumeAgentEnrollToken :one
UPDATE agent_enroll_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING tenant_id, server_id
`

type ConsumeAgentEnrollTokenRow struct {
	TenantID uuid.UUID
	ServerID uuid.UUID
}

// Single statement so two redemptions of the same token cannot both succeed. Run
// all-tenants: the tenant is only known once the token resolves.
func (q *Queries) ConsumeAgentEnrollToken(ctx context.Context, tokenHash string) (ConsumeAgentEnrollTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeAgentEnrollToken, tokenHash)
	var i ConsumeAgentEnrollTokenRow
	err := row.Scan(&i.TenantID, &i.ServerID)
	return i, err
}

const deleteUnusedAgentEnrollTokensByServer = `-- name: DeleteUnusedAgentEnrollTokensByServer :exec
DELETE FROM agent_enroll_tokens
WHERE server_id = $1 AND used_at IS NULL
`

// A server keeps one live token: creating a new one drops the older unused ones.
func (q *Queries) DeleteUnusedAgentEnrollTokensByServer(ctx context.Context, serverID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnusedAgentEnrollTokensByServer, serverID)
	return err
}

const insertAgentEnrollToken = `-- name: InsertAgentEnrollToken :exec
INSERT INTO agent_enroll_tokens (tenant_id, server_id, token_hash, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAgentEnrollTokenParams struct {
	TenantID  uuid.UUID
	ServerID  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedBy *uuid.UUID
}

func (q *Queries) InsertAgentEnrollToken(ctx context.Context, arg InsertAgentEnrollTokenParams) error {
	_, err := q.db.Exec(ctx, insertAgentEnrollToken,
		arg.TenantID,
		arg.ServerID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}
