// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_enroll_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAgentEnrollToken = `-- name: ConsumeAgentEnrollToken :one
UPDATE agent_enroll_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING tenant_id, server_id
`

type ConsumeAgentEnrollTokenRow struct {
	TenantID uuid.UUID
	ServerID uuid.UUID
}

// Single statement so two redemptions of the same token cannot both succeed. Run
// all-tenants: the tenant is only known once the token resolves.
func (q *Queries) ConsumeAgentEnrollToken(ctx context.Context, tokenHash string) (ConsumeAgentEnrollTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeAgentEnrollToken, tokenHash)
	var i ConsumeAgentEnrollTokenRow
	err := row.Scan(&i.TenantID, &i.ServerID)
	return i, err
}

const upsertAgentEnrollToken = `-- name: UpsertAgentEnrollToken :one
INSERT INTO agent_enroll_tokens (tenant_id, server_id, token_hash, expires_at, created_by)
VALUES ($1, $2, $3, now() + make_interval(secs => $4::float8), $5)
ON CONFLICT (server_id) WHERE used_at IS NULL DO UPDATE
SET token_hash = EXCLUDED.token_hash, expires_at = EXCLUDED.expires_at,
    created_by = EXCLUDED.created_by, created_at = now()
RETURNING expires_at
`

type UpsertAgentEnrollTokenParams struct {
	TenantID   uuid.UUID
	ServerID   uuid.UUID
	TokenHash  string
	TtlSeconds float64
	CreatedBy  *uuid.UUID
}

// A server keeps one live token: the partial unique index makes a concurrent or repeated
// creation replace the unused row instead of adding a second. expires_at comes from the
// database clock, the same one ConsumeAgentEnrollToken checks it against.
func (q *Queries) UpsertAgentEnrollToken(ctx context.Context, arg UpsertAgentEnrollTokenParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, upsertAgentEnrollToken,
		arg.TenantID,
		arg.ServerID,
		arg.TokenHash,
		arg.TtlSeconds,
		arg.CreatedBy,
	)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}
