// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_ca.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAgentCA = `-- name: GetAgentCA :one
SELECT id, cert_pem, key_sealed, created_at
FROM agent_ca
WHERE id = 1
`

func (q *Queries) GetAgentCA(ctx context.Context) (AgentCa, error) {
	row := q.db.QueryRow(ctx, getAgentCA)
	var i AgentCa
	err := row.Scan(
		&i.ID,
		&i.CertPem,
		&i.KeySealed,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentCertificate = `-- name: GetAgentCertificate :one
SELECT serial, tenant_id, server_id, fingerprint, not_before, not_after, revoked_at, created_at
FROM agent_certificates
WHERE serial = $1
`

func (q *Queries) GetAgentCertificate(ctx context.Context, serial string) (AgentCertificate, error) {
	row := q.db.QueryRow(ctx, getAgentCertificate, serial)
	var i AgentCertificate
	err := row.Scan(
		&i.Serial,
		&i.TenantID,
		&i.ServerID,
		&i.Fingerprint,
		&i.NotBefore,
		&i.NotAfter,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgentCAIfAbsent = `-- name: InsertAgentCAIfAbsent :execrows
INSERT INTO agent_ca (id, cert_pem, key_sealed)
VALUES (1, $1, $2)
ON CONFLICT (id) DO NOTHING
`

type InsertAgentCAIfAbsentParams struct {
	CertPem   string
	KeySealed []byte
}

// Concurrent first callers race here; the loser inserts nothing and re-reads.
func (q *Queries) InsertAgentCAIfAbsent(ctx context.Context, arg InsertAgentCAIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAgentCAIfAbsent, arg.CertPem, arg.KeySealed)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAgentCertificate = `-- name: InsertAgentCertificate :exec
INSERT INTO agent_certificates (serial, tenant_id, server_id, fingerprint, not_before, not_after)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAgentCertificateParams struct {
	Serial      string
	TenantID    uuid.UUID
	ServerID    uuid.UUID
	Fingerprint string
	NotBefore   time.Time
	NotAfter    time.Time
}

func (q *Queries) InsertAgentCertificate(ctx context.Context, arg InsertAgentCertificateParams) error {
	_, err := q.db.Exec(ctx, insertAgentCertificate,
		arg.Serial,
		arg.TenantID,
		arg.ServerID,
		arg.Fingerprint,
		arg.NotBefore,
		arg.NotAfter,
	)
	return err
}

const listAgentCertificatesByServer = `-- name: ListAgentCertificatesByServer :many
SELECT serial, tenant_id, server_id, fingerprint, not_before, not_after, revoked_at, created_at
FROM agent_certificates
WHERE server_id = $1
ORDER BY not_after DESC
`

func (q *Queries) ListAgentCertificatesByServer(ctx context.Context, serverID uuid.UUID) ([]AgentCertificate, error) {
	rows, err := q.db.Query(ctx, listAgentCertificatesByServer, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCertificate{}
	for rows.Next() {
		var i AgentCertificate
		if err := rows.Scan(
			&i.Serial,
			&i.TenantID,
			&i.ServerID,
			&i.Fingerprint,
			&i.NotBefore,
			&i.NotAfter,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRenewableAgentCertificate = `-- name: LockRenewableAgentCertificate :one
SELECT (now() >= not_before + (not_after - not_before) / 2)::boolean AS renewable
FROM agent_certificates
WHERE serial = $1 AND server_id = $2 AND tenant_id = $3
  AND (revoked_at IS NULL OR revoked_at > now())
FOR UPDATE
`

type LockRenewableAgentCertificateParams struct {
	Serial   string
	ServerID uuid.UUID
	TenantID uuid.UUID
}

// The certificate an agent presents to renew: it must belong to the server and tenant, and not
// be revoked yet (a revocation in the future is a grace period and still counts). Locked so
// concurrent renewals with the same certificate run one after the other. renewable is the
// database-clock test for the minimum age: half of the certificate's lifetime has passed.
func (q *Queries) LockRenewableAgentCertificate(ctx context.Context, arg LockRenewableAgentCertificateParams) (bool, error) {
	row := q.db.QueryRow(ctx, lockRenewableAgentCertificate, arg.Serial, arg.ServerID, arg.TenantID)
	var renewable bool
	err := row.Scan(&renewable)
	return renewable, err
}

const revokeAgentCertificate = `-- name: RevokeAgentCertificate :execrows
UPDATE agent_certificates SET revoked_at = now()
WHERE serial = $1 AND (revoked_at IS NULL OR revoked_at > now())
`

// A revoked_at in the future is a grace period after a renewal; revoking ends it now. A date
// already in the past keeps its first value.
func (q *Queries) RevokeAgentCertificate(ctx context.Context, serial string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAgentCertificate, serial)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAgentCertificatesByServer = `-- name: RevokeAgentCertificatesByServer :execrows
UPDATE agent_certificates SET revoked_at = now()
WHERE server_id = $1 AND (revoked_at IS NULL OR revoked_at > now())
`

func (q *Queries) RevokeAgentCertificatesByServer(ctx context.Context, serverID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAgentCertificatesByServer, serverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeAgentCertificates = `-- name: SupersedeAgentCertificates :execrows
UPDATE agent_certificates SET revoked_at = now() + make_interval(secs => $1::float8)
WHERE server_id = $2 AND tenant_id = $3 AND serial <> $4
  AND not_after > now()
  AND (revoked_at IS NULL OR revoked_at > now() + make_interval(secs => $1::float8))
`

type SupersedeAgentCertificatesParams struct {
	GraceSeconds float64
	ServerID     uuid.UUID
	TenantID     uuid.UUID
	KeepSerial   string
}

// Ends the server's other live certificates grace seconds from now, unless they already end
// sooner. Expired ones are left alone.
func (q *Queries) SupersedeAgentCertificates(ctx context.Context, arg SupersedeAgentCertificatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeAgentCertificates,
		arg.GraceSeconds,
		arg.ServerID,
		arg.TenantID,
		arg.KeepSerial,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
