// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alarms.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignAlarm = `-- name: AssignAlarm :one
UPDATE alarms
SET assigned_to = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, tenant_id, site_id, camera_id, event_id, source, status, assigned_to, acknowledged_by, acknowledged_at, resolved_by, resolved_at, created_at, updated_at
`

type AssignAlarmParams struct {
	AssignedTo *uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) AssignAlarm(ctx context.Context, arg AssignAlarmParams) (Alarm, error) {
	row := q.db.QueryRow(ctx, assignAlarm, arg.AssignedTo, arg.ID)
	var i Alarm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.CameraID,
		&i.EventID,
		&i.Source,
		&i.Status,
		&i.AssignedTo,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlarm = `-- name: GetAlarm :one
SELECT a.id, a.tenant_id, a.site_id, a.camera_id, a.event_id, a.source, a.status,
       a.assigned_to, a.acknowledged_by, a.acknowledged_at, a.resolved_by, a.resolved_at,
       a.created_at, a.updated_at,
       s.name AS site_name,
       c.display_name AS camera_name,
       e.severity AS event_severity,
       e.start_time AS event_start_time,
       e.end_time AS event_end_time,
       e.labels AS event_labels,
       e.sub_labels AS event_sub_labels,
       COALESCE(u_assignee.display_name, '')::text AS assigned_to_name,
       COALESCE(u_ack.display_name, '')::text AS acknowledged_by_name,
       COALESCE(u_res.display_name, '')::text AS resolved_by_name
FROM alarms a
JOIN sites s ON s.id = a.site_id
JOIN cameras c ON c.id = a.camera_id
JOIN events e ON e.id = a.event_id
LEFT JOIN users u_assignee ON u_assignee.id = a.assigned_to
LEFT JOIN users u_ack ON u_ack.id = a.acknowledged_by
LEFT JOIN users u_res ON u_res.id = a.resolved_by
WHERE a.id = $1
`

type GetAlarmRow struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	SiteID             uuid.UUID
	CameraID           uuid.UUID
	EventID            uuid.UUID
	Source             string
	Status             string
	AssignedTo         *uuid.UUID
	AcknowledgedBy     *uuid.UUID
	AcknowledgedAt     *time.Time
	ResolvedBy         *uuid.UUID
	ResolvedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SiteName           string
	CameraName         string
	EventSeverity      string
	EventStartTime     time.Time
	EventEndTime       *time.Time
	EventLabels        []string
	EventSubLabels     []string
	AssignedToName     string
	AcknowledgedByName string
	ResolvedByName     string
}

func (q *Queries) GetAlarm(ctx context.Context, id uuid.UUID) (GetAlarmRow, error) {
	row := q.db.QueryRow(ctx, getAlarm, id)
	var i GetAlarmRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.CameraID,
		&i.EventID,
		&i.Source,
		&i.Status,
		&i.AssignedTo,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteName,
		&i.CameraName,
		&i.EventSeverity,
		&i.EventStartTime,
		&i.EventEndTime,
		&i.EventLabels,
		&i.EventSubLabels,
		&i.AssignedToName,
		&i.AcknowledgedByName,
		&i.ResolvedByName,
	)
	return i, err
}

const listAlarms = `-- name: ListAlarms :many
SELECT a.id, a.tenant_id, a.site_id, a.camera_id, a.event_id, a.source, a.status,
       a.assigned_to, a.acknowledged_by, a.acknowledged_at, a.resolved_by, a.resolved_at,
       a.created_at, a.updated_at,
       s.name AS site_name,
       c.display_name AS camera_name,
       e.severity AS event_severity,
       e.start_time AS event_start_time,
       e.end_time AS event_end_time,
       e.labels AS event_labels,
       e.sub_labels AS event_sub_labels,
       COALESCE(u_assignee.display_name, '')::text AS assigned_to_name,
       COALESCE(u_ack.display_name, '')::text AS acknowledged_by_name,
       COALESCE(u_res.display_name, '')::text AS resolved_by_name
FROM alarms a
JOIN sites s ON s.id = a.site_id
JOIN cameras c ON c.id = a.camera_id
JOIN events e ON e.id = a.event_id
LEFT JOIN users u_assignee ON u_assignee.id = a.assigned_to
LEFT JOIN users u_ack ON u_ack.id = a.acknowledged_by
LEFT JOIN users u_res ON u_res.id = a.resolved_by
WHERE a.camera_id = ANY($1::uuid[])
  AND ($2::text IS NULL OR a.status = $2)
  AND ($3::uuid IS NULL OR a.site_id = $3)
  AND ($4::uuid IS NULL OR a.camera_id = $4)
  AND ($5::uuid IS NULL OR a.assigned_to = $5)
ORDER BY a.created_at DESC
LIMIT $6
`

type ListAlarmsParams struct {
	CameraIds  []uuid.UUID
	Status     *string
	SiteID     *uuid.UUID
	CameraID   *uuid.UUID
	AssignedTo *uuid.UUID
	LimitCount int32
}

type ListAlarmsRow struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	SiteID             uuid.UUID
	CameraID           uuid.UUID
	EventID            uuid.UUID
	Source             string
	Status             string
	AssignedTo         *uuid.UUID
	AcknowledgedBy     *uuid.UUID
	AcknowledgedAt     *time.Time
	ResolvedBy         *uuid.UUID
	ResolvedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SiteName           string
	CameraName         string
	EventSeverity      string
	EventStartTime     time.Time
	EventEndTime       *time.Time
	EventLabels        []string
	EventSubLabels     []string
	AssignedToName     string
	AcknowledgedByName string
	ResolvedByName     string
}

func (q *Queries) ListAlarms(ctx context.Context, arg ListAlarmsParams) ([]ListAlarmsRow, error) {
	rows, err := q.db.Query(ctx, listAlarms,
		arg.CameraIds,
		arg.Status,
		arg.SiteID,
		arg.CameraID,
		arg.AssignedTo,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlarmsRow{}
	for rows.Next() {
		var i ListAlarmsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.CameraID,
			&i.EventID,
			&i.Source,
			&i.Status,
			&i.AssignedTo,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SiteName,
			&i.CameraName,
			&i.EventSeverity,
			&i.EventStartTime,
			&i.EventEndTime,
			&i.EventLabels,
			&i.EventSubLabels,
			&i.AssignedToName,
			&i.AcknowledgedByName,
			&i.ResolvedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlarmStatus = `-- name: UpdateAlarmStatus :one
UPDATE alarms
SET status = $1,
    acknowledged_by = CASE WHEN $1 = 'acknowledged' THEN $2 ELSE acknowledged_by END,
    acknowledged_at = CASE WHEN $1 = 'acknowledged' THEN now() ELSE acknowledged_at END,
    resolved_by = CASE WHEN $1 = 'resolved' THEN $2 ELSE resolved_by END,
    resolved_at = CASE WHEN $1 = 'resolved' THEN now() ELSE resolved_at END,
    updated_at = now()
WHERE id = $3
RETURNING id, tenant_id, site_id, camera_id, event_id, source, status, assigned_to, acknowledged_by, acknowledged_at, resolved_by, resolved_at, created_at, updated_at
`

type UpdateAlarmStatusParams struct {
	Status  string
	ActorID *uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) UpdateAlarmStatus(ctx context.Context, arg UpdateAlarmStatusParams) (Alarm, error) {
	row := q.db.QueryRow(ctx, updateAlarmStatus, arg.Status, arg.ActorID, arg.ID)
	var i Alarm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.CameraID,
		&i.EventID,
		&i.Source,
		&i.Status,
		&i.AssignedTo,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const usersWithCameraPermission = `-- name: UsersWithCameraPermission :many
WITH live_camera AS (
    SELECT c.id, c.tenant_id, c.site_id, c.server_id FROM cameras c WHERE c.id = $1::uuid AND c.deleted_at IS NULL
), covering AS (
    SELECT 'platform'::text AS scope_type, NULL::uuid AS scope_id FROM live_camera
    UNION ALL SELECT 'tenant', tenant_id FROM live_camera
    UNION ALL SELECT 'site', site_id FROM live_camera
    UNION ALL SELECT 'server', server_id FROM live_camera
    UNION ALL SELECT 'camera', id FROM live_camera
    UNION ALL SELECT 'camera_group', m.group_id FROM camera_group_members m
        JOIN camera_groups cg ON cg.id = m.group_id AND cg.deleted_at IS NULL
        JOIN live_camera ON live_camera.id = m.camera_id
), matching_grants AS (
    SELECT g.subject_type, g.subject_id, g.effect
    FROM permission_grants g
    JOIN covering cv ON cv.scope_type = g.scope_type AND cv.scope_id IS NOT DISTINCT FROM g.scope_id
    WHERE g.permission = $2::text
), user_eval AS (
    SELECT u.id, u.username, u.display_name, mg.effect
    FROM users u
    JOIN live_camera lc ON lc.tenant_id = u.tenant_id
    JOIN matching_grants mg ON mg.subject_type = 'user' AND mg.subject_id = u.id
    WHERE u.deleted_at IS NULL
    UNION ALL
    SELECT u.id, u.username, u.display_name, mg.effect
    FROM users u
    JOIN live_camera lc ON lc.tenant_id = u.tenant_id
    JOIN user_group_members m ON m.user_id = u.id
    JOIN user_groups ug ON ug.id = m.group_id AND ug.deleted_at IS NULL
    JOIN matching_grants mg ON mg.subject_type = 'group' AND mg.subject_id = ug.id
    WHERE u.deleted_at IS NULL
)
SELECT id, username, display_name
FROM user_eval
GROUP BY id, username, display_name
HAVING bool_or(effect = 'allow') AND NOT bool_or(effect = 'deny')
ORDER BY display_name
`

type UsersWithCameraPermissionParams struct {
	CameraID   uuid.UUID
	Permission string
}

type UsersWithCameraPermissionRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
}

func (q *Queries) UsersWithCameraPermission(ctx context.Context, arg UsersWithCameraPermissionParams) ([]UsersWithCameraPermissionRow, error) {
	rows, err := q.db.Query(ctx, usersWithCameraPermission, arg.CameraID, arg.Permission)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsersWithCameraPermissionRow{}
	for rows.Next() {
		var i UsersWithCameraPermissionRow
		if err := rows.Scan(&i.ID, &i.Username, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
