// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (tenant_id, actor_id, actor_name, action, target_type, target_id, request_id, ip, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditParams struct {
	TenantID   *uuid.UUID
	ActorID    *uuid.UUID
	ActorName  string
	Action     string
	TargetType string
	TargetID   *uuid.UUID
	RequestID  string
	Ip         *netip.Addr
	Details    json.RawMessage
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.TenantID,
		arg.ActorID,
		arg.ActorName,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.Ip,
		arg.Details,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, occurred_at, tenant_id, actor_id, actor_name, action, target_type, target_id, request_id, ip, details FROM audit_log
WHERE ($1::uuid IS NULL OR tenant_id = $1)
  AND ($2::bool OR tenant_id IS NOT NULL)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::uuid IS NULL OR actor_id = $4)
  AND ($5::timestamptz IS NULL OR occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR occurred_at < $6)
  AND ($7::bigint IS NULL OR id < $7)
ORDER BY id DESC
LIMIT $8
`

type ListAuditParams struct {
	TenantID   *uuid.UUID
	AllTenants bool
	Action     *string
	ActorID    *uuid.UUID
	FromTime   *time.Time
	ToTime     *time.Time
	BeforeID   *int64
	MaxRows    int32
}

func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.TenantID,
		arg.AllTenants,
		arg.Action,
		arg.ActorID,
		arg.FromTime,
		arg.ToTime,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.TenantID,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.Ip,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
