// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branding.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTenantBranding = `-- name: GetTenantBranding :one
SELECT tenant_id, owner_name, logo_key, logo_content_type, updated_at, updated_by FROM tenant_branding WHERE tenant_id = $1
`

func (q *Queries) GetTenantBranding(ctx context.Context, tenantID uuid.UUID) (TenantBranding, error) {
	row := q.db.QueryRow(ctx, getTenantBranding, tenantID)
	var i TenantBranding
	err := row.Scan(
		&i.TenantID,
		&i.OwnerName,
		&i.LogoKey,
		&i.LogoContentType,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertTenantBranding = `-- name: UpsertTenantBranding :one
INSERT INTO tenant_branding (tenant_id, owner_name, logo_key, logo_content_type, updated_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id) DO UPDATE SET
    owner_name = EXCLUDED.owner_name,
    logo_key = EXCLUDED.logo_key,
    logo_content_type = EXCLUDED.logo_content_type,
    updated_at = now(),
    updated_by = EXCLUDED.updated_by
RETURNING tenant_id, owner_name, logo_key, logo_content_type, updated_at, updated_by
`

type UpsertTenantBrandingParams struct {
	TenantID        uuid.UUID
	OwnerName       string
	LogoKey         string
	LogoContentType string
	UpdatedBy       *uuid.UUID
}

func (q *Queries) UpsertTenantBranding(ctx context.Context, arg UpsertTenantBrandingParams) (TenantBranding, error) {
	row := q.db.QueryRow(ctx, upsertTenantBranding,
		arg.TenantID,
		arg.OwnerName,
		arg.LogoKey,
		arg.LogoContentType,
		arg.UpdatedBy,
	)
	var i TenantBranding
	err := row.Scan(
		&i.TenantID,
		&i.OwnerName,
		&i.LogoKey,
		&i.LogoContentType,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
