// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clipwatermark.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimNextClipWatermarkJob = `-- name: ClaimNextClipWatermarkJob :one
UPDATE clip_watermark_jobs SET status = 'running', updated_at = now()
WHERE id = (
    SELECT id FROM clip_watermark_jobs
    WHERE status = 'queued'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, tenant_id, site_id, server_id, camera_id, lpr_read_id, remote_event_id, requested_by, watermark_text, logo_key, status, error, output_key, created_at, updated_at
`

func (q *Queries) ClaimNextClipWatermarkJob(ctx context.Context) (ClipWatermarkJob, error) {
	row := q.db.QueryRow(ctx, claimNextClipWatermarkJob)
	var i ClipWatermarkJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ServerID,
		&i.CameraID,
		&i.LprReadID,
		&i.RemoteEventID,
		&i.RequestedBy,
		&i.WatermarkText,
		&i.LogoKey,
		&i.Status,
		&i.Error,
		&i.OutputKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClipWatermarkJob = `-- name: GetClipWatermarkJob :one
SELECT id, tenant_id, site_id, server_id, camera_id, lpr_read_id, remote_event_id, requested_by, watermark_text, logo_key, status, error, output_key, created_at, updated_at FROM clip_watermark_jobs WHERE id = $1
`

func (q *Queries) GetClipWatermarkJob(ctx context.Context, id uuid.UUID) (ClipWatermarkJob, error) {
	row := q.db.QueryRow(ctx, getClipWatermarkJob, id)
	var i ClipWatermarkJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ServerID,
		&i.CameraID,
		&i.LprReadID,
		&i.RemoteEventID,
		&i.RequestedBy,
		&i.WatermarkText,
		&i.LogoKey,
		&i.Status,
		&i.Error,
		&i.OutputKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertClipWatermarkJob = `-- name: InsertClipWatermarkJob :one
INSERT INTO clip_watermark_jobs
    (tenant_id, site_id, server_id, camera_id, lpr_read_id, remote_event_id, requested_by, watermark_text, logo_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, site_id, server_id, camera_id, lpr_read_id, remote_event_id, requested_by, watermark_text, logo_key, status, error, output_key, created_at, updated_at
`

type InsertClipWatermarkJobParams struct {
	TenantID      uuid.UUID
	SiteID        uuid.UUID
	ServerID      uuid.UUID
	CameraID      uuid.UUID
	LprReadID     uuid.UUID
	RemoteEventID string
	RequestedBy   uuid.UUID
	WatermarkText string
	LogoKey       string
}

func (q *Queries) InsertClipWatermarkJob(ctx context.Context, arg InsertClipWatermarkJobParams) (ClipWatermarkJob, error) {
	row := q.db.QueryRow(ctx, insertClipWatermarkJob,
		arg.TenantID,
		arg.SiteID,
		arg.ServerID,
		arg.CameraID,
		arg.LprReadID,
		arg.RemoteEventID,
		arg.RequestedBy,
		arg.WatermarkText,
		arg.LogoKey,
	)
	var i ClipWatermarkJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ServerID,
		&i.CameraID,
		&i.LprReadID,
		&i.RemoteEventID,
		&i.RequestedBy,
		&i.WatermarkText,
		&i.LogoKey,
		&i.Status,
		&i.Error,
		&i.OutputKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markClipWatermarkJobDone = `-- name: MarkClipWatermarkJobDone :exec
UPDATE clip_watermark_jobs SET status = 'done', output_key = $1, updated_at = now() WHERE id = $2
`

type MarkClipWatermarkJobDoneParams struct {
	OutputKey string
	ID        uuid.UUID
}

func (q *Queries) MarkClipWatermarkJobDone(ctx context.Context, arg MarkClipWatermarkJobDoneParams) error {
	_, err := q.db.Exec(ctx, markClipWatermarkJobDone, arg.OutputKey, arg.ID)
	return err
}

const markClipWatermarkJobFailed = `-- name: MarkClipWatermarkJobFailed :exec
UPDATE clip_watermark_jobs SET status = 'failed', error = $1, updated_at = now() WHERE id = $2
`

type MarkClipWatermarkJobFailedParams struct {
	Error string
	ID    uuid.UUID
}

func (q *Queries) MarkClipWatermarkJobFailed(ctx context.Context, arg MarkClipWatermarkJobFailedParams) error {
	_, err := q.db.Exec(ctx, markClipWatermarkJobFailed, arg.Error, arg.ID)
	return err
}

const setClipWatermarkJobLogoKey = `-- name: SetClipWatermarkJobLogoKey :exec
UPDATE clip_watermark_jobs SET logo_key = $1, updated_at = now() WHERE id = $2
`

type SetClipWatermarkJobLogoKeyParams struct {
	LogoKey string
	ID      uuid.UUID
}

func (q *Queries) SetClipWatermarkJobLogoKey(ctx context.Context, arg SetClipWatermarkJobLogoKeyParams) error {
	_, err := q.db.Exec(ctx, setClipWatermarkJobLogoKey, arg.LogoKey, arg.ID)
	return err
}
