// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: frigate_config.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getFrigateConfigRevision = `-- name: GetFrigateConfigRevision :one
SELECT id, tenant_id, server_id, camera_id, actor_user_id, actor_name, kind, sections, before_yaml, after_yaml, patch, created_at FROM frigate_config_revisions WHERE id = $1 AND server_id = $2
`

type GetFrigateConfigRevisionParams struct {
	ID       uuid.UUID
	ServerID uuid.UUID
}

func (q *Queries) GetFrigateConfigRevision(ctx context.Context, arg GetFrigateConfigRevisionParams) (FrigateConfigRevision, error) {
	row := q.db.QueryRow(ctx, getFrigateConfigRevision, arg.ID, arg.ServerID)
	var i FrigateConfigRevision
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ServerID,
		&i.CameraID,
		&i.ActorUserID,
		&i.ActorName,
		&i.Kind,
		&i.Sections,
		&i.BeforeYaml,
		&i.AfterYaml,
		&i.Patch,
		&i.CreatedAt,
	)
	return i, err
}

const insertFrigateConfigRevision = `-- name: InsertFrigateConfigRevision :one
INSERT INTO frigate_config_revisions (tenant_id, server_id, camera_id, actor_user_id, actor_name, kind, sections, before_yaml, after_yaml, patch)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, server_id, camera_id, actor_user_id, actor_name, kind, sections, patch, created_at
`

type InsertFrigateConfigRevisionParams struct {
	TenantID    uuid.UUID
	ServerID    uuid.UUID
	CameraID    *uuid.UUID
	ActorUserID *uuid.UUID
	ActorName   string
	Kind        string
	Sections    []string
	BeforeYaml  string
	AfterYaml   string
	Patch       json.RawMessage
}

type InsertFrigateConfigRevisionRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ServerID    uuid.UUID
	CameraID    *uuid.UUID
	ActorUserID *uuid.UUID
	ActorName   string
	Kind        string
	Sections    []string
	Patch       json.RawMessage
	CreatedAt   time.Time
}

func (q *Queries) InsertFrigateConfigRevision(ctx context.Context, arg InsertFrigateConfigRevisionParams) (InsertFrigateConfigRevisionRow, error) {
	row := q.db.QueryRow(ctx, insertFrigateConfigRevision,
		arg.TenantID,
		arg.ServerID,
		arg.CameraID,
		arg.ActorUserID,
		arg.ActorName,
		arg.Kind,
		arg.Sections,
		arg.BeforeYaml,
		arg.AfterYaml,
		arg.Patch,
	)
	var i InsertFrigateConfigRevisionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ServerID,
		&i.CameraID,
		&i.ActorUserID,
		&i.ActorName,
		&i.Kind,
		&i.Sections,
		&i.Patch,
		&i.CreatedAt,
	)
	return i, err
}

const listFrigateConfigRevisions = `-- name: ListFrigateConfigRevisions :many
SELECT id, tenant_id, server_id, camera_id, actor_user_id, actor_name, kind, sections, patch, created_at
FROM frigate_config_revisions
WHERE server_id = $1
  AND ($2::uuid IS NULL OR camera_id = $2)
  AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListFrigateConfigRevisionsParams struct {
	ServerID uuid.UUID
	CameraID *uuid.UUID
	Before   *time.Time
	MaxRows  int32
}

type ListFrigateConfigRevisionsRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	ServerID    uuid.UUID
	CameraID    *uuid.UUID
	ActorUserID *uuid.UUID
	ActorName   string
	Kind        string
	Sections    []string
	Patch       json.RawMessage
	CreatedAt   time.Time
}

func (q *Queries) ListFrigateConfigRevisions(ctx context.Context, arg ListFrigateConfigRevisionsParams) ([]ListFrigateConfigRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listFrigateConfigRevisions,
		arg.ServerID,
		arg.CameraID,
		arg.Before,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFrigateConfigRevisionsRow{}
	for rows.Next() {
		var i ListFrigateConfigRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ServerID,
			&i.CameraID,
			&i.ActorUserID,
			&i.ActorName,
			&i.Kind,
			&i.Sections,
			&i.Patch,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
