// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const authorizedCameraIDs = `-- name: AuthorizedCameraIDs :many

WITH subjects AS (
    SELECT 'user'::text AS subject_type, $1::uuid AS subject_id
    UNION ALL
    SELECT 'group', m.group_id FROM user_group_members m
    JOIN user_groups ug ON ug.id = m.group_id AND ug.deleted_at IS NULL
    WHERE m.user_id = $1::uuid
), grants AS (
    SELECT g.effect, g.scope_type, g.scope_id FROM permission_grants g
    JOIN subjects s ON s.subject_type = g.subject_type AND s.subject_id = g.subject_id
    WHERE g.permission = $2::text
), live AS (
    SELECT c.id, c.tenant_id, c.site_id, c.server_id FROM cameras c WHERE c.deleted_at IS NULL
), covering AS (
    SELECT id AS camera_id, 'platform'::text AS scope_type, NULL::uuid AS scope_id FROM live
    UNION ALL SELECT id, 'tenant', tenant_id FROM live
    UNION ALL SELECT id, 'site', site_id FROM live
    UNION ALL SELECT id, 'server', server_id FROM live
    UNION ALL SELECT id, 'camera', id FROM live
    UNION ALL SELECT m.camera_id, 'camera_group', m.group_id FROM camera_group_members m
        JOIN camera_groups cg ON cg.id = m.group_id AND cg.deleted_at IS NULL
        JOIN live ON live.id = m.camera_id
)
SELECT cv.camera_id::uuid FROM covering cv
JOIN grants g ON g.scope_type = cv.scope_type AND g.scope_id IS NOT DISTINCT FROM cv.scope_id
GROUP BY cv.camera_id
HAVING bool_or(g.effect = 'allow') AND NOT bool_or(g.effect = 'deny')
`

type AuthorizedCameraIDsParams struct {
	UserID     uuid.UUID
	Permission string
}

// Authorized-ID queries implement authz.Decide in SQL so list endpoints filter in the
// database (PRD §31): a row is visible when some ALLOW covers it and no DENY does.
func (q *Queries) AuthorizedCameraIDs(ctx context.Context, arg AuthorizedCameraIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, authorizedCameraIDs, arg.UserID, arg.Permission)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var cv_camera_id uuid.UUID
		if err := rows.Scan(&cv_camera_id); err != nil {
			return nil, err
		}
		items = append(items, cv_camera_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorizedServerIDs = `-- name: AuthorizedServerIDs :many
WITH subjects AS (
    SELECT 'user'::text AS subject_type, $1::uuid AS subject_id
    UNION ALL
    SELECT 'group', m.group_id FROM user_group_members m
    JOIN user_groups ug ON ug.id = m.group_id AND ug.deleted_at IS NULL
    WHERE m.user_id = $1::uuid
), grants AS (
    SELECT g.effect, g.scope_type, g.scope_id FROM permission_grants g
    JOIN subjects s ON s.subject_type = g.subject_type AND s.subject_id = g.subject_id
    WHERE g.permission = $2::text
), live AS (
    SELECT s.id, s.tenant_id, s.site_id FROM frigate_servers s WHERE s.deleted_at IS NULL
), covering AS (
    SELECT id AS server_id, 'platform'::text AS scope_type, NULL::uuid AS scope_id FROM live
    UNION ALL SELECT id, 'tenant', tenant_id FROM live
    UNION ALL SELECT id, 'site', site_id FROM live
    UNION ALL SELECT id, 'server', id FROM live
)
SELECT cv.server_id::uuid FROM covering cv
JOIN grants g ON g.scope_type = cv.scope_type AND g.scope_id IS NOT DISTINCT FROM cv.scope_id
GROUP BY cv.server_id
HAVING bool_or(g.effect = 'allow') AND NOT bool_or(g.effect = 'deny')
`

type AuthorizedServerIDsParams struct {
	UserID     uuid.UUID
	Permission string
}

func (q *Queries) AuthorizedServerIDs(ctx context.Context, arg AuthorizedServerIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, authorizedServerIDs, arg.UserID, arg.Permission)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var cv_server_id uuid.UUID
		if err := rows.Scan(&cv_server_id); err != nil {
			return nil, err
		}
		items = append(items, cv_server_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authorizedSiteIDs = `-- name: AuthorizedSiteIDs :many
WITH subjects AS (
    SELECT 'user'::text AS subject_type, $1::uuid AS subject_id
    UNION ALL
    SELECT 'group', m.group_id FROM user_group_members m
    JOIN user_groups ug ON ug.id = m.group_id AND ug.deleted_at IS NULL
    WHERE m.user_id = $1::uuid
), grants AS (
    SELECT g.effect, g.scope_type, g.scope_id FROM permission_grants g
    JOIN subjects s ON s.subject_type = g.subject_type AND s.subject_id = g.subject_id
    WHERE g.permission = $2::text
), live AS (
    SELECT s.id, s.tenant_id FROM sites s WHERE s.deleted_at IS NULL
), covering AS (
    SELECT id AS site_id, 'platform'::text AS scope_type, NULL::uuid AS scope_id FROM live
    UNION ALL SELECT id, 'tenant', tenant_id FROM live
    UNION ALL SELECT id, 'site', id FROM live
)
SELECT cv.site_id::uuid FROM covering cv
JOIN grants g ON g.scope_type = cv.scope_type AND g.scope_id IS NOT DISTINCT FROM cv.scope_id
GROUP BY cv.site_id
HAVING bool_or(g.effect = 'allow') AND NOT bool_or(g.effect = 'deny')
`

type AuthorizedSiteIDsParams struct {
	UserID     uuid.UUID
	Permission string
}

func (q *Queries) AuthorizedSiteIDs(ctx context.Context, arg AuthorizedSiteIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, authorizedSiteIDs, arg.UserID, arg.Permission)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var cv_site_id uuid.UUID
		if err := rows.Scan(&cv_site_id); err != nil {
			return nil, err
		}
		items = append(items, cv_site_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO permission_grants (tenant_id, subject_type, subject_id, permission, effect, scope_type, scope_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, subject_type, subject_id, permission, effect, scope_type, scope_id, created_by, created_at
`

type CreateGrantParams struct {
	TenantID    *uuid.UUID
	SubjectType string
	SubjectID   uuid.UUID
	Permission  string
	Effect      string
	ScopeType   string
	ScopeID     *uuid.UUID
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.TenantID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Permission,
		arg.Effect,
		arg.ScopeType,
		arg.ScopeID,
		arg.CreatedBy,
	)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Permission,
		&i.Effect,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGrant = `-- name: DeleteGrant :exec
DELETE FROM permission_grants WHERE id = $1
`

func (q *Queries) DeleteGrant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGrant, id)
	return err
}

const getGrant = `-- name: GetGrant :one
SELECT id, tenant_id, subject_type, subject_id, permission, effect, scope_type, scope_id, created_by, created_at FROM permission_grants WHERE id = $1
`

func (q *Queries) GetGrant(ctx context.Context, id uuid.UUID) (PermissionGrant, error) {
	row := q.db.QueryRow(ctx, getGrant, id)
	var i PermissionGrant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Permission,
		&i.Effect,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listGrants = `-- name: ListGrants :many
SELECT id, tenant_id, subject_type, subject_id, permission, effect, scope_type, scope_id, created_by, created_at FROM permission_grants
WHERE ($1::text IS NULL OR subject_type = $1)
  AND ($2::uuid IS NULL OR subject_id = $2)
  AND ($3::uuid IS NULL OR tenant_id = $3)
ORDER BY created_at
`

type ListGrantsParams struct {
	SubjectType *string
	SubjectID   *uuid.UUID
	TenantID    *uuid.UUID
}

func (q *Queries) ListGrants(ctx context.Context, arg ListGrantsParams) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listGrants, arg.SubjectType, arg.SubjectID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Permission,
			&i.Effect,
			&i.ScopeType,
			&i.ScopeID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForUser = `-- name: ListGrantsForUser :many
SELECT g.id, g.tenant_id, g.subject_type, g.subject_id, g.permission, g.effect, g.scope_type, g.scope_id, g.created_by, g.created_at
FROM permission_grants g
WHERE (g.subject_type = 'user' AND g.subject_id = $1)
   OR (g.subject_type = 'group' AND g.subject_id IN (
        SELECT m.group_id FROM user_group_members m
        JOIN user_groups ug ON ug.id = m.group_id AND ug.deleted_at IS NULL
        WHERE m.user_id = $1))
`

// Every grant that reaches the user directly or through an active group.
func (q *Queries) ListGrantsForUser(ctx context.Context, userID uuid.UUID) ([]PermissionGrant, error) {
	rows, err := q.db.Query(ctx, listGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PermissionGrant{}
	for rows.Next() {
		var i PermissionGrant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Permission,
			&i.Effect,
			&i.ScopeType,
			&i.ScopeID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
