// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_group_members (group_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserToGroupParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.Exec(ctx, addUserToGroup, arg.GroupID, arg.UserID)
	return err
}

const clearGroupMembers = `-- name: ClearGroupMembers :exec
DELETE FROM user_group_members WHERE group_id = $1
`

func (q *Queries) ClearGroupMembers(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearGroupMembers, groupID)
	return err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAPITokenParams struct {
	UserID    uuid.UUID
	Name      string
	TokenHash []byte
	ExpiresAt *time.Time
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	Ip        *netip.Addr
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, username, email, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, username, email, display_name, status, created_at, updated_at, deleted_at, deleted_by, password_hash, password_changed_at, must_change_password, mfa_secret_sealed, mfa_enabled, failed_logins, locked_until, last_login_at
`

type CreateUserParams struct {
	TenantID    *uuid.UUID
	Username    string
	Email       *string
	DisplayName string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Username,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.MfaSecretSealed,
		&i.MfaEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
	)
	return i, err
}

const createUserGroup = `-- name: CreateUserGroup :one
INSERT INTO user_groups (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, created_at, updated_at, deleted_at, deleted_by
`

type CreateUserGroupParams struct {
	TenantID    *uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateUserGroup(ctx context.Context, arg CreateUserGroupParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, createUserGroup, arg.TenantID, arg.Name, arg.Description)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getActorBySessionHash = `-- name: GetActorBySessionHash :one
SELECT u.id, u.tenant_id, u.username, u.display_name, s.id AS session_id, s.last_seen_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND s.last_seen_at > now() - make_interval(secs => $2::float8)
  AND u.status = 'active'
  AND u.deleted_at IS NULL
`

type GetActorBySessionHashParams struct {
	TokenHash   []byte
	IdleSeconds float64
}

type GetActorBySessionHashRow struct {
	ID          uuid.UUID
	TenantID    *uuid.UUID
	Username    string
	DisplayName string
	SessionID   uuid.UUID
	LastSeenAt  time.Time
}

func (q *Queries) GetActorBySessionHash(ctx context.Context, arg GetActorBySessionHashParams) (GetActorBySessionHashRow, error) {
	row := q.db.QueryRow(ctx, getActorBySessionHash, arg.TokenHash, arg.IdleSeconds)
	var i GetActorBySessionHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.SessionID,
		&i.LastSeenAt,
	)
	return i, err
}

const getActorByTokenHash = `-- name: GetActorByTokenHash :one
SELECT u.id, u.tenant_id, u.username, u.display_name, t.id AS token_id
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now())
  AND u.status = 'active'
  AND u.deleted_at IS NULL
`

type GetActorByTokenHashRow struct {
	ID          uuid.UUID
	TenantID    *uuid.UUID
	Username    string
	DisplayName string
	TokenID     uuid.UUID
}

func (q *Queries) GetActorByTokenHash(ctx context.Context, tokenHash []byte) (GetActorByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActorByTokenHash, tokenHash)
	var i GetActorByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.DisplayName,
		&i.TokenID,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, username, email, display_name, status, created_at, updated_at, deleted_at, deleted_by, password_hash, password_changed_at, must_change_password, mfa_secret_sealed, mfa_enabled, failed_logins, locked_until, last_login_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.MfaSecretSealed,
		&i.MfaEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, tenant_id, username, email, display_name, status, created_at, updated_at, deleted_at, deleted_by, password_hash, password_changed_at, must_change_password, mfa_secret_sealed, mfa_enabled, failed_logins, locked_until, last_login_at FROM users WHERE lower(username) = lower($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.MfaSecretSealed,
		&i.MfaEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserGroup = `-- name: GetUserGroup :one
SELECT id, tenant_id, name, description, created_at, updated_at, deleted_at, deleted_by FROM user_groups WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserGroup(ctx context.Context, id uuid.UUID) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getUserGroup, id)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getUserGroupByName = `-- name: GetUserGroupByName :one
SELECT id, tenant_id, name, description, created_at, updated_at, deleted_at, deleted_by FROM user_groups
WHERE tenant_id IS NOT DISTINCT FROM $1 AND lower(name) = lower($2) AND deleted_at IS NULL
`

type GetUserGroupByNameParams struct {
	TenantID *uuid.UUID
	Name     string
}

func (q *Queries) GetUserGroupByName(ctx context.Context, arg GetUserGroupByNameParams) (UserGroup, error) {
	row := q.db.QueryRow(ctx, getUserGroupByName, arg.TenantID, arg.Name)
	var i UserGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT user_id FROM user_group_members WHERE group_id = $1 ORDER BY user_id
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupIDs = `-- name: ListUserGroupIDs :many
SELECT m.group_id FROM user_group_members m
JOIN user_groups g ON g.id = m.group_id AND g.deleted_at IS NULL
WHERE m.user_id = $1 ORDER BY m.group_id
`

func (q *Queries) ListUserGroupIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserGroupIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var group_id uuid.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.tenant_id, g.name, g.description, g.created_at, g.updated_at, g.deleted_at, g.deleted_by, (SELECT count(*) FROM user_group_members m WHERE m.group_id = g.id)::int AS member_count
FROM user_groups g
WHERE g.deleted_at IS NULL
  AND ($1::uuid IS NULL OR g.tenant_id = $1)
  AND ($2::bool OR g.tenant_id IS NOT NULL)
ORDER BY lower(g.name)
`

type ListUserGroupsParams struct {
	TenantID        *uuid.UUID
	IncludePlatform bool
}

type ListUserGroupsRow struct {
	ID          uuid.UUID
	TenantID    *uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	DeletedBy   *uuid.UUID
	MemberCount int32
}

func (q *Queries) ListUserGroups(ctx context.Context, arg ListUserGroupsParams) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, arg.TenantID, arg.IncludePlatform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserGroupsRow{}
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, username, email, display_name, status, created_at, updated_at, deleted_at, deleted_by, password_hash, password_changed_at, must_change_password, mfa_secret_sealed, mfa_enabled, failed_logins, locked_until, last_login_at FROM users
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR tenant_id = $1)
  AND ($2::bool OR tenant_id IS NOT NULL)
ORDER BY lower(username)
`

type ListUsersParams struct {
	TenantID        *uuid.UUID
	IncludePlatform bool
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.TenantID, arg.IncludePlatform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.PasswordHash,
			&i.PasswordChangedAt,
			&i.MustChangePassword,
			&i.MfaSecretSealed,
			&i.MfaEnabled,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :one
UPDATE users SET
    failed_logins = failed_logins + 1,
    locked_until = CASE WHEN failed_logins + 1 >= $1::int THEN now() + make_interval(secs => $2::float8) ELSE locked_until END
WHERE id = $3
RETURNING failed_logins, locked_until
`

type RecordLoginFailureParams struct {
	MaxFailures int32
	LockSeconds float64
	ID          uuid.UUID
}

type RecordLoginFailureRow struct {
	FailedLogins int32
	LockedUntil  *time.Time
}

func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) (RecordLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordLoginFailure, arg.MaxFailures, arg.LockSeconds, arg.ID)
	var i RecordLoginFailureRow
	err := row.Scan(&i.FailedLogins, &i.LockedUntil)
	return i, err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE users SET failed_logins = 0, locked_until = NULL, last_login_at = now() WHERE id = $1
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, id)
	return err
}

const removeUserFromGroups = `-- name: RemoveUserFromGroups :exec
DELETE FROM user_group_members WHERE user_id = $1
`

func (q *Queries) RemoveUserFromGroups(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeUserFromGroups, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
  AND ($2::uuid IS NULL OR id <> $2)
`

type RevokeUserSessionsParams struct {
	UserID uuid.UUID
	Keep   *uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.UserID, arg.Keep)
	return err
}

const setMFASecret = `-- name: SetMFASecret :exec
UPDATE users SET mfa_secret_sealed = $1, mfa_enabled = $2, updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type SetMFASecretParams struct {
	MfaSecretSealed []byte
	MfaEnabled      bool
	ID              uuid.UUID
}

func (q *Queries) SetMFASecret(ctx context.Context, arg SetMFASecretParams) error {
	_, err := q.db.Exec(ctx, setMFASecret, arg.MfaSecretSealed, arg.MfaEnabled, arg.ID)
	return err
}

const setPassword = `-- name: SetPassword :exec
UPDATE users SET password_hash = $1, password_changed_at = now(),
    must_change_password = $2, failed_logins = 0, locked_until = NULL, updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type SetPasswordParams struct {
	PasswordHash       string
	MustChangePassword bool
	ID                 uuid.UUID
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.PasswordHash, arg.MustChangePassword, arg.ID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = now(), deleted_by = $1, status = 'disabled' WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.DeletedBy, arg.ID)
	return err
}

const softDeleteUserGroup = `-- name: SoftDeleteUserGroup :exec
UPDATE user_groups SET deleted_at = now(), deleted_by = $1 WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteUserGroupParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteUserGroup(ctx context.Context, arg SoftDeleteUserGroupParams) error {
	_, err := q.db.Exec(ctx, softDeleteUserGroup, arg.DeletedBy, arg.ID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now()
WHERE id = $1 AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now()
WHERE id = $1 AND last_seen_at < now() - interval '30 seconds'
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    display_name = coalesce($1, display_name),
    email = coalesce($2, email),
    status = coalesce($3, status),
    updated_at = now()
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	DisplayName *string
	Email       *string
	Status      *string
	ID          uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.DisplayName,
		arg.Email,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateUserGroup = `-- name: UpdateUserGroup :exec
UPDATE user_groups SET name = $1, description = $2, updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateUserGroupParams struct {
	Name        string
	Description string
	ID          uuid.UUID
}

func (q *Queries) UpdateUserGroup(ctx context.Context, arg UpdateUserGroupParams) error {
	_, err := q.db.Exec(ctx, updateUserGroup, arg.Name, arg.Description, arg.ID)
	return err
}
