// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addCameraGroupMembers = `-- name: AddCameraGroupMembers :exec
INSERT INTO camera_group_members (group_id, camera_id, tenant_id)
SELECT $1, c.id, c.tenant_id FROM cameras c
WHERE c.id = ANY($2::uuid[]) AND c.tenant_id = $3 AND c.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type AddCameraGroupMembersParams struct {
	GroupID   uuid.UUID
	CameraIds []uuid.UUID
	TenantID  uuid.UUID
}

func (q *Queries) AddCameraGroupMembers(ctx context.Context, arg AddCameraGroupMembersParams) error {
	_, err := q.db.Exec(ctx, addCameraGroupMembers, arg.GroupID, arg.CameraIds, arg.TenantID)
	return err
}

const clearCameraGroupMembers = `-- name: ClearCameraGroupMembers :exec
DELETE FROM camera_group_members WHERE group_id = $1
`

func (q *Queries) ClearCameraGroupMembers(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCameraGroupMembers, groupID)
	return err
}

const countCamerasInTenant = `-- name: CountCamerasInTenant :one
SELECT count(*)::int FROM cameras WHERE id = ANY($1::uuid[]) AND tenant_id = $2 AND deleted_at IS NULL
`

type CountCamerasInTenantParams struct {
	Ids      []uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) CountCamerasInTenant(ctx context.Context, arg CountCamerasInTenantParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCamerasInTenant, arg.Ids, arg.TenantID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCameraGroup = `-- name: CreateCameraGroup :one
INSERT INTO camera_groups (tenant_id, name, description) VALUES ($1, $2, $3) RETURNING id, tenant_id, name, description, created_at, updated_at, deleted_at, deleted_by
`

type CreateCameraGroupParams struct {
	TenantID    uuid.UUID
	Name        string
	Description string
}

func (q *Queries) CreateCameraGroup(ctx context.Context, arg CreateCameraGroupParams) (CameraGroup, error) {
	row := q.db.QueryRow(ctx, createCameraGroup, arg.TenantID, arg.Name, arg.Description)
	var i CameraGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const createServer = `-- name: CreateServer :exec
INSERT INTO frigate_servers (id, tenant_id, site_id, name, base_url, auth_mode, username, password_sealed, tls_skip_verify, frigate_version, capabilities)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateServerParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SiteID         uuid.UUID
	Name           string
	BaseUrl        string
	AuthMode       string
	Username       string
	PasswordSealed []byte
	TlsSkipVerify  bool
	FrigateVersion string
	Capabilities   json.RawMessage
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) error {
	_, err := q.db.Exec(ctx, createServer,
		arg.ID,
		arg.TenantID,
		arg.SiteID,
		arg.Name,
		arg.BaseUrl,
		arg.AuthMode,
		arg.Username,
		arg.PasswordSealed,
		arg.TlsSkipVerify,
		arg.FrigateVersion,
		arg.Capabilities,
	)
	return err
}

const createSite = `-- name: CreateSite :one
INSERT INTO sites (tenant_id, name, timezone, address)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateSiteParams struct {
	TenantID uuid.UUID
	Name     string
	Timezone string
	Address  string
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.TenantID,
		arg.Name,
		arg.Timezone,
		arg.Address,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (slug, name) VALUES ($1, $2) RETURNING id, slug, name, created_at, updated_at, deleted_at, deleted_by
`

type CreateTenantParams struct {
	Slug string
	Name string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Slug, arg.Name)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getCamera = `-- name: GetCamera :one
SELECT c.id, c.tenant_id, c.site_id, c.server_id, c.remote_name, c.display_name, c.enabled, c.zones, c.lpr, c.live_stream, c.hq_stream, c.status, c.fps, c.missing_since, c.created_at, c.updated_at, c.deleted_at, c.deleted_by,
    coalesce((SELECT array_agg(m.group_id ORDER BY m.group_id) FROM camera_group_members m
              JOIN camera_groups g ON g.id = m.group_id AND g.deleted_at IS NULL
              WHERE m.camera_id = c.id), '{}')::uuid[] AS group_ids
FROM cameras c WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCameraRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SiteID       uuid.UUID
	ServerID     uuid.UUID
	RemoteName   string
	DisplayName  string
	Enabled      bool
	Zones        []string
	Lpr          bool
	LiveStream   string
	HqStream     string
	Status       string
	Fps          *float32
	MissingSince *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	DeletedBy    *uuid.UUID
	GroupIds     []uuid.UUID
}

func (q *Queries) GetCamera(ctx context.Context, id uuid.UUID) (GetCameraRow, error) {
	row := q.db.QueryRow(ctx, getCamera, id)
	var i GetCameraRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.ServerID,
		&i.RemoteName,
		&i.DisplayName,
		&i.Enabled,
		&i.Zones,
		&i.Lpr,
		&i.LiveStream,
		&i.HqStream,
		&i.Status,
		&i.Fps,
		&i.MissingSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.GroupIds,
	)
	return i, err
}

const getCameraGroup = `-- name: GetCameraGroup :one
SELECT id, tenant_id, name, description, created_at, updated_at, deleted_at, deleted_by FROM camera_groups WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCameraGroup(ctx context.Context, id uuid.UUID) (CameraGroup, error) {
	row := q.db.QueryRow(ctx, getCameraGroup, id)
	var i CameraGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getServer = `-- name: GetServer :one
SELECT fs.id, fs.tenant_id, fs.site_id, fs.name, fs.base_url, fs.username, fs.password_sealed, fs.tls_skip_verify, fs.frigate_version, fs.capabilities, fs.status, fs.last_seen_at, fs.last_checked_at, fs.last_error, fs.stats, fs.created_at, fs.updated_at, fs.deleted_at, fs.deleted_by, fs.auth_mode,
    (SELECT count(*) FROM cameras c WHERE c.server_id = fs.id AND c.deleted_at IS NULL)::int AS camera_count
FROM frigate_servers fs WHERE fs.id = $1 AND fs.deleted_at IS NULL
`

type GetServerRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SiteID         uuid.UUID
	Name           string
	BaseUrl        string
	Username       string
	PasswordSealed []byte
	TlsSkipVerify  bool
	FrigateVersion string
	Capabilities   json.RawMessage
	Status         string
	LastSeenAt     *time.Time
	LastCheckedAt  *time.Time
	LastError      string
	Stats          json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
	DeletedBy      *uuid.UUID
	AuthMode       string
	CameraCount    int32
}

func (q *Queries) GetServer(ctx context.Context, id uuid.UUID) (GetServerRow, error) {
	row := q.db.QueryRow(ctx, getServer, id)
	var i GetServerRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.BaseUrl,
		&i.Username,
		&i.PasswordSealed,
		&i.TlsSkipVerify,
		&i.FrigateVersion,
		&i.Capabilities,
		&i.Status,
		&i.LastSeenAt,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Stats,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.AuthMode,
		&i.CameraCount,
	)
	return i, err
}

const getServerRow = `-- name: GetServerRow :one
SELECT id, tenant_id, site_id, name, base_url, username, password_sealed, tls_skip_verify, frigate_version, capabilities, status, last_seen_at, last_checked_at, last_error, stats, created_at, updated_at, deleted_at, deleted_by, auth_mode FROM frigate_servers WHERE id = $1 AND deleted_at IS NULL
`

// Full row with the sealed credentials, for code that connects to Frigate.
func (q *Queries) GetServerRow(ctx context.Context, id uuid.UUID) (FrigateServer, error) {
	row := q.db.QueryRow(ctx, getServerRow, id)
	var i FrigateServer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.BaseUrl,
		&i.Username,
		&i.PasswordSealed,
		&i.TlsSkipVerify,
		&i.FrigateVersion,
		&i.Capabilities,
		&i.Status,
		&i.LastSeenAt,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Stats,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.AuthMode,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT s.id, s.tenant_id, s.name, s.timezone, s.address, s.created_at, s.updated_at, s.deleted_at, s.deleted_by,
    (SELECT count(*) FROM frigate_servers fs WHERE fs.site_id = s.id AND fs.deleted_at IS NULL)::int AS server_count
FROM sites s WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetSiteRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Timezone    string
	Address     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	DeletedBy   *uuid.UUID
	ServerCount int32
}

func (q *Queries) GetSite(ctx context.Context, id uuid.UUID) (GetSiteRow, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i GetSiteRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Timezone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.ServerCount,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, slug, name, created_at, updated_at, deleted_at, deleted_by FROM tenants WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, name, created_at, updated_at, deleted_at, deleted_by FROM tenants WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listAllActiveServers = `-- name: ListAllActiveServers :many
SELECT id, tenant_id, site_id, name, base_url, username, password_sealed, tls_skip_verify, frigate_version, capabilities, status, last_seen_at, last_checked_at, last_error, stats, created_at, updated_at, deleted_at, deleted_by, auth_mode FROM frigate_servers WHERE deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListAllActiveServers(ctx context.Context) ([]FrigateServer, error) {
	rows, err := q.db.Query(ctx, listAllActiveServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FrigateServer{}
	for rows.Next() {
		var i FrigateServer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Name,
			&i.BaseUrl,
			&i.Username,
			&i.PasswordSealed,
			&i.TlsSkipVerify,
			&i.FrigateVersion,
			&i.Capabilities,
			&i.Status,
			&i.LastSeenAt,
			&i.LastCheckedAt,
			&i.LastError,
			&i.Stats,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.AuthMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraGroupMembers = `-- name: ListCameraGroupMembers :many
SELECT camera_id FROM camera_group_members WHERE group_id = $1 ORDER BY camera_id
`

func (q *Queries) ListCameraGroupMembers(ctx context.Context, groupID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listCameraGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var camera_id uuid.UUID
		if err := rows.Scan(&camera_id); err != nil {
			return nil, err
		}
		items = append(items, camera_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraGroups = `-- name: ListCameraGroups :many
SELECT id, tenant_id, name, description, created_at, updated_at, deleted_at, deleted_by FROM camera_groups WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR tenant_id = $1)
ORDER BY name
`

func (q *Queries) ListCameraGroups(ctx context.Context, tenantID *uuid.UUID) ([]CameraGroup, error) {
	rows, err := q.db.Query(ctx, listCameraGroups, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraGroup{}
	for rows.Next() {
		var i CameraGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameras = `-- name: ListCameras :many
SELECT c.id, c.tenant_id, c.site_id, c.server_id, c.remote_name, c.display_name, c.enabled, c.zones, c.lpr, c.live_stream, c.hq_stream, c.status, c.fps, c.missing_since, c.created_at, c.updated_at, c.deleted_at, c.deleted_by,
    coalesce((SELECT array_agg(m.group_id ORDER BY m.group_id) FROM camera_group_members m
              JOIN camera_groups g ON g.id = m.group_id AND g.deleted_at IS NULL
              WHERE m.camera_id = c.id), '{}')::uuid[] AS group_ids
FROM cameras c
WHERE c.deleted_at IS NULL
  AND c.id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR c.site_id = $2)
  AND ($3::uuid IS NULL OR c.server_id = $3)
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM camera_group_members m WHERE m.camera_id = c.id AND m.group_id = $4))
  AND ($5::text IS NULL
       OR c.display_name ILIKE '%' || $5 || '%'
       OR c.remote_name ILIKE '%' || $5 || '%')
ORDER BY c.display_name
`

type ListCamerasParams struct {
	Ids      []uuid.UUID
	SiteID   *uuid.UUID
	ServerID *uuid.UUID
	GroupID  *uuid.UUID
	Q        *string
}

type ListCamerasRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SiteID       uuid.UUID
	ServerID     uuid.UUID
	RemoteName   string
	DisplayName  string
	Enabled      bool
	Zones        []string
	Lpr          bool
	LiveStream   string
	HqStream     string
	Status       string
	Fps          *float32
	MissingSince *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	DeletedBy    *uuid.UUID
	GroupIds     []uuid.UUID
}

func (q *Queries) ListCameras(ctx context.Context, arg ListCamerasParams) ([]ListCamerasRow, error) {
	rows, err := q.db.Query(ctx, listCameras,
		arg.Ids,
		arg.SiteID,
		arg.ServerID,
		arg.GroupID,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCamerasRow{}
	for rows.Next() {
		var i ListCamerasRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.ServerID,
			&i.RemoteName,
			&i.DisplayName,
			&i.Enabled,
			&i.Zones,
			&i.Lpr,
			&i.LiveStream,
			&i.HqStream,
			&i.Status,
			&i.Fps,
			&i.MissingSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.GroupIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerCameras = `-- name: ListServerCameras :many
SELECT id, tenant_id, site_id, server_id, remote_name, display_name, enabled, zones, lpr, live_stream, hq_stream, status, fps, missing_since, created_at, updated_at, deleted_at, deleted_by FROM cameras WHERE server_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListServerCameras(ctx context.Context, serverID uuid.UUID) ([]Camera, error) {
	rows, err := q.db.Query(ctx, listServerCameras, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Camera{}
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.ServerID,
			&i.RemoteName,
			&i.DisplayName,
			&i.Enabled,
			&i.Zones,
			&i.Lpr,
			&i.LiveStream,
			&i.HqStream,
			&i.Status,
			&i.Fps,
			&i.MissingSince,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServers = `-- name: ListServers :many
SELECT fs.id, fs.tenant_id, fs.site_id, fs.name, fs.base_url, fs.username, fs.password_sealed, fs.tls_skip_verify, fs.frigate_version, fs.capabilities, fs.status, fs.last_seen_at, fs.last_checked_at, fs.last_error, fs.stats, fs.created_at, fs.updated_at, fs.deleted_at, fs.deleted_by, fs.auth_mode,
    (SELECT count(*) FROM cameras c WHERE c.server_id = fs.id AND c.deleted_at IS NULL)::int AS camera_count
FROM frigate_servers fs
WHERE fs.deleted_at IS NULL
  AND fs.id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR fs.site_id = $2)
ORDER BY fs.name
`

type ListServersParams struct {
	Ids    []uuid.UUID
	SiteID *uuid.UUID
}

type ListServersRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SiteID         uuid.UUID
	Name           string
	BaseUrl        string
	Username       string
	PasswordSealed []byte
	TlsSkipVerify  bool
	FrigateVersion string
	Capabilities   json.RawMessage
	Status         string
	LastSeenAt     *time.Time
	LastCheckedAt  *time.Time
	LastError      string
	Stats          json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
	DeletedBy      *uuid.UUID
	AuthMode       string
	CameraCount    int32
}

func (q *Queries) ListServers(ctx context.Context, arg ListServersParams) ([]ListServersRow, error) {
	rows, err := q.db.Query(ctx, listServers, arg.Ids, arg.SiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServersRow{}
	for rows.Next() {
		var i ListServersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Name,
			&i.BaseUrl,
			&i.Username,
			&i.PasswordSealed,
			&i.TlsSkipVerify,
			&i.FrigateVersion,
			&i.Capabilities,
			&i.Status,
			&i.LastSeenAt,
			&i.LastCheckedAt,
			&i.LastError,
			&i.Stats,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.AuthMode,
			&i.CameraCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT s.id, s.tenant_id, s.name, s.timezone, s.address, s.created_at, s.updated_at, s.deleted_at, s.deleted_by,
    (SELECT count(*) FROM frigate_servers fs WHERE fs.site_id = s.id AND fs.deleted_at IS NULL)::int AS server_count
FROM sites s
WHERE s.deleted_at IS NULL
  AND s.id = ANY($1::uuid[])
  AND ($2::uuid IS NULL OR s.tenant_id = $2)
ORDER BY s.name
`

type ListSitesParams struct {
	Ids      []uuid.UUID
	TenantID *uuid.UUID
}

type ListSitesRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Timezone    string
	Address     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	DeletedBy   *uuid.UUID
	ServerCount int32
}

func (q *Queries) ListSites(ctx context.Context, arg ListSitesParams) ([]ListSitesRow, error) {
	rows, err := q.db.Query(ctx, listSites, arg.Ids, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesRow{}
	for rows.Next() {
		var i ListSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Timezone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.ServerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, name, created_at, updated_at, deleted_at, deleted_by FROM tenants
WHERE deleted_at IS NULL AND ($1::uuid IS NULL OR id = $1)
ORDER BY name
`

func (q *Queries) ListTenants(ctx context.Context, id *uuid.UUID) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissingCameras = `-- name: MarkMissingCameras :execrows
UPDATE cameras SET missing_since = coalesce(missing_since, now()), status = 'offline', updated_at = now()
WHERE server_id = $1 AND deleted_at IS NULL AND NOT (remote_name = ANY($2::text[]))
`

type MarkMissingCamerasParams struct {
	ServerID uuid.UUID
	Present  []string
}

func (q *Queries) MarkMissingCameras(ctx context.Context, arg MarkMissingCamerasParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMissingCameras, arg.ServerID, arg.Present)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveServerCameras = `-- name: MoveServerCameras :exec
UPDATE cameras SET site_id = $1, updated_at = now() WHERE server_id = $2
`

type MoveServerCamerasParams struct {
	SiteID   uuid.UUID
	ServerID uuid.UUID
}

func (q *Queries) MoveServerCameras(ctx context.Context, arg MoveServerCamerasParams) error {
	_, err := q.db.Exec(ctx, moveServerCameras, arg.SiteID, arg.ServerID)
	return err
}

const setServerCamerasStatus = `-- name: SetServerCamerasStatus :exec
UPDATE cameras SET status = $1 WHERE server_id = $2 AND deleted_at IS NULL
`

type SetServerCamerasStatusParams struct {
	Status   string
	ServerID uuid.UUID
}

func (q *Queries) SetServerCamerasStatus(ctx context.Context, arg SetServerCamerasStatusParams) error {
	_, err := q.db.Exec(ctx, setServerCamerasStatus, arg.Status, arg.ServerID)
	return err
}

const softDeleteCameraGroup = `-- name: SoftDeleteCameraGroup :exec
UPDATE camera_groups SET deleted_at = now(), deleted_by = $1 WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteCameraGroupParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteCameraGroup(ctx context.Context, arg SoftDeleteCameraGroupParams) error {
	_, err := q.db.Exec(ctx, softDeleteCameraGroup, arg.DeletedBy, arg.ID)
	return err
}

const softDeleteServer = `-- name: SoftDeleteServer :exec
UPDATE frigate_servers SET deleted_at = now(), deleted_by = $1 WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteServerParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteServer(ctx context.Context, arg SoftDeleteServerParams) error {
	_, err := q.db.Exec(ctx, softDeleteServer, arg.DeletedBy, arg.ID)
	return err
}

const softDeleteServerCameras = `-- name: SoftDeleteServerCameras :exec
UPDATE cameras SET deleted_at = now(), deleted_by = $1 WHERE server_id = $2 AND deleted_at IS NULL
`

type SoftDeleteServerCamerasParams struct {
	DeletedBy *uuid.UUID
	ServerID  uuid.UUID
}

func (q *Queries) SoftDeleteServerCameras(ctx context.Context, arg SoftDeleteServerCamerasParams) error {
	_, err := q.db.Exec(ctx, softDeleteServerCameras, arg.DeletedBy, arg.ServerID)
	return err
}

const softDeleteSite = `-- name: SoftDeleteSite :exec
UPDATE sites SET deleted_at = now(), deleted_by = $1 WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteSiteParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteSite(ctx context.Context, arg SoftDeleteSiteParams) error {
	_, err := q.db.Exec(ctx, softDeleteSite, arg.DeletedBy, arg.ID)
	return err
}

const updateCamera = `-- name: UpdateCamera :exec
UPDATE cameras SET
    display_name = coalesce($1, display_name),
    enabled = coalesce($2, enabled),
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateCameraParams struct {
	DisplayName *string
	Enabled     *bool
	ID          uuid.UUID
}

func (q *Queries) UpdateCamera(ctx context.Context, arg UpdateCameraParams) error {
	_, err := q.db.Exec(ctx, updateCamera, arg.DisplayName, arg.Enabled, arg.ID)
	return err
}

const updateCameraGroup = `-- name: UpdateCameraGroup :exec
UPDATE camera_groups SET name = $1, description = $2, updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateCameraGroupParams struct {
	Name        string
	Description string
	ID          uuid.UUID
}

func (q *Queries) UpdateCameraGroup(ctx context.Context, arg UpdateCameraGroupParams) error {
	_, err := q.db.Exec(ctx, updateCameraGroup, arg.Name, arg.Description, arg.ID)
	return err
}

const updateCameraHealth = `-- name: UpdateCameraHealth :exec
UPDATE cameras SET status = $1, fps = $2
WHERE server_id = $3 AND remote_name = $4 AND deleted_at IS NULL AND missing_since IS NULL
`

type UpdateCameraHealthParams struct {
	Status     string
	Fps        *float32
	ServerID   uuid.UUID
	RemoteName string
}

func (q *Queries) UpdateCameraHealth(ctx context.Context, arg UpdateCameraHealthParams) error {
	_, err := q.db.Exec(ctx, updateCameraHealth,
		arg.Status,
		arg.Fps,
		arg.ServerID,
		arg.RemoteName,
	)
	return err
}

const updateServer = `-- name: UpdateServer :exec
UPDATE frigate_servers SET
    name = $1, site_id = $2, base_url = $3, auth_mode = $4, username = $5,
    password_sealed = $6, tls_skip_verify = $7, updated_at = now()
WHERE id = $8 AND deleted_at IS NULL
`

type UpdateServerParams struct {
	Name           string
	SiteID         uuid.UUID
	BaseUrl        string
	AuthMode       string
	Username       string
	PasswordSealed []byte
	TlsSkipVerify  bool
	ID             uuid.UUID
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) error {
	_, err := q.db.Exec(ctx, updateServer,
		arg.Name,
		arg.SiteID,
		arg.BaseUrl,
		arg.AuthMode,
		arg.Username,
		arg.PasswordSealed,
		arg.TlsSkipVerify,
		arg.ID,
	)
	return err
}

const updateServerDiscovery = `-- name: UpdateServerDiscovery :exec
UPDATE frigate_servers SET frigate_version = $1, capabilities = $2, updated_at = now()
WHERE id = $3
`

type UpdateServerDiscoveryParams struct {
	FrigateVersion string
	Capabilities   json.RawMessage
	ID             uuid.UUID
}

func (q *Queries) UpdateServerDiscovery(ctx context.Context, arg UpdateServerDiscoveryParams) error {
	_, err := q.db.Exec(ctx, updateServerDiscovery, arg.FrigateVersion, arg.Capabilities, arg.ID)
	return err
}

const updateServerHealth = `-- name: UpdateServerHealth :exec
UPDATE frigate_servers SET
    status = $1,
    last_checked_at = now(),
    last_seen_at = CASE WHEN $2::bool THEN now() ELSE last_seen_at END,
    last_error = $3,
    stats = CASE WHEN $2::bool THEN $4 ELSE stats END,
    frigate_version = CASE WHEN $5::text <> '' THEN $5 ELSE frigate_version END
WHERE id = $6
`

type UpdateServerHealthParams struct {
	Status         string
	Reachable      bool
	LastError      string
	Stats          json.RawMessage
	FrigateVersion string
	ID             uuid.UUID
}

func (q *Queries) UpdateServerHealth(ctx context.Context, arg UpdateServerHealthParams) error {
	_, err := q.db.Exec(ctx, updateServerHealth,
		arg.Status,
		arg.Reachable,
		arg.LastError,
		arg.Stats,
		arg.FrigateVersion,
		arg.ID,
	)
	return err
}

const updateSite = `-- name: UpdateSite :exec
UPDATE sites SET
    name = coalesce($1, name),
    timezone = coalesce($2, timezone),
    address = coalesce($3, address),
    updated_at = now()
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateSiteParams struct {
	Name     *string
	Timezone *string
	Address  *string
	ID       uuid.UUID
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) error {
	_, err := q.db.Exec(ctx, updateSite,
		arg.Name,
		arg.Timezone,
		arg.Address,
		arg.ID,
	)
	return err
}

const upsertCamera = `-- name: UpsertCamera :one
INSERT INTO cameras (tenant_id, site_id, server_id, remote_name, display_name, enabled, zones, lpr, live_stream, hq_stream)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (server_id, remote_name) WHERE deleted_at IS NULL DO UPDATE SET
    zones = excluded.zones,
    lpr = excluded.lpr,
    live_stream = excluded.live_stream,
    hq_stream = excluded.hq_stream,
    missing_since = NULL,
    updated_at = now()
RETURNING (xmax = 0) AS inserted
`

type UpsertCameraParams struct {
	TenantID    uuid.UUID
	SiteID      uuid.UUID
	ServerID    uuid.UUID
	RemoteName  string
	DisplayName string
	Enabled     bool
	Zones       []string
	Lpr         bool
	LiveStream  string
	HqStream    string
}

func (q *Queries) UpsertCamera(ctx context.Context, arg UpsertCameraParams) (bool, error) {
	row := q.db.QueryRow(ctx, upsertCamera,
		arg.TenantID,
		arg.SiteID,
		arg.ServerID,
		arg.RemoteName,
		arg.DisplayName,
		arg.Enabled,
		arg.Zones,
		arg.Lpr,
		arg.LiveStream,
		arg.HqStream,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}
