// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maps.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createMapBuilding = `-- name: CreateMapBuilding :one
INSERT INTO map_buildings (tenant_id, site_id, name, footprint, lat, lng)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, site_id, name, footprint, lat, lng, revision, created_at, updated_at, deleted_at
`

type CreateMapBuildingParams struct {
	TenantID  uuid.UUID
	SiteID    uuid.UUID
	Name      string
	Footprint []byte
	Lat       *float64
	Lng       *float64
}

func (q *Queries) CreateMapBuilding(ctx context.Context, arg CreateMapBuildingParams) (MapBuilding, error) {
	row := q.db.QueryRow(ctx, createMapBuilding,
		arg.TenantID,
		arg.SiteID,
		arg.Name,
		arg.Footprint,
		arg.Lat,
		arg.Lng,
	)
	var i MapBuilding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Footprint,
		&i.Lat,
		&i.Lng,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMapDevice = `-- name: CreateMapDevice :one
INSERT INTO map_devices (tenant_id, site_id, kind, name, status, props)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, site_id, kind, name, status, props, created_at, updated_at, deleted_at
`

type CreateMapDeviceParams struct {
	TenantID uuid.UUID
	SiteID   uuid.UUID
	Kind     string
	Name     string
	Status   string
	Props    json.RawMessage
}

func (q *Queries) CreateMapDevice(ctx context.Context, arg CreateMapDeviceParams) (MapDevice, error) {
	row := q.db.QueryRow(ctx, createMapDevice,
		arg.TenantID,
		arg.SiteID,
		arg.Kind,
		arg.Name,
		arg.Status,
		arg.Props,
	)
	var i MapDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Props,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMapFloor = `-- name: CreateMapFloor :one
INSERT INTO map_floors (
    tenant_id, building_id, name, ordinal, plan_key, plan_content_type, plan_width_px, plan_height_px, georef
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, building_id, name, ordinal, plan_key, plan_content_type, plan_width_px, plan_height_px, georef, revision, created_at, updated_at, deleted_at
`

type CreateMapFloorParams struct {
	TenantID        uuid.UUID
	BuildingID      uuid.UUID
	Name            string
	Ordinal         int32
	PlanKey         string
	PlanContentType string
	PlanWidthPx     *int32
	PlanHeightPx    *int32
	Georef          []byte
}

func (q *Queries) CreateMapFloor(ctx context.Context, arg CreateMapFloorParams) (MapFloor, error) {
	row := q.db.QueryRow(ctx, createMapFloor,
		arg.TenantID,
		arg.BuildingID,
		arg.Name,
		arg.Ordinal,
		arg.PlanKey,
		arg.PlanContentType,
		arg.PlanWidthPx,
		arg.PlanHeightPx,
		arg.Georef,
	)
	var i MapFloor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildingID,
		&i.Name,
		&i.Ordinal,
		&i.PlanKey,
		&i.PlanContentType,
		&i.PlanWidthPx,
		&i.PlanHeightPx,
		&i.Georef,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMapRegion = `-- name: CreateMapRegion :one
INSERT INTO map_regions (tenant_id, parent_id, name)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, parent_id, name, created_at
`

type CreateMapRegionParams struct {
	TenantID uuid.UUID
	ParentID *uuid.UUID
	Name     string
}

func (q *Queries) CreateMapRegion(ctx context.Context, arg CreateMapRegionParams) (MapRegion, error) {
	row := q.db.QueryRow(ctx, createMapRegion, arg.TenantID, arg.ParentID, arg.Name)
	var i MapRegion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createMapView = `-- name: CreateMapView :one
INSERT INTO map_views (tenant_id, owner_id, name, shared, state)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, owner_id, name, shared, state, created_at, updated_at, deleted_at
`

type CreateMapViewParams struct {
	TenantID uuid.UUID
	OwnerID  uuid.UUID
	Name     string
	Shared   bool
	State    json.RawMessage
}

func (q *Queries) CreateMapView(ctx context.Context, arg CreateMapViewParams) (MapView, error) {
	row := q.db.QueryRow(ctx, createMapView,
		arg.TenantID,
		arg.OwnerID,
		arg.Name,
		arg.Shared,
		arg.State,
	)
	var i MapView
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMapZone = `-- name: CreateMapZone :one
INSERT INTO map_zones (
    tenant_id, site_id, floor_id, name, kind, geometry,
    min_lat, min_lng, max_lat, max_lng, style, metadata,
    revision, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    coalesce($11::jsonb, '{}'::jsonb),
    coalesce($12::jsonb, '{}'::jsonb),
    nextval('map_revision'), $13, $13
)
RETURNING id, tenant_id, site_id, floor_id, name, kind, geometry, min_lat, min_lng, max_lat, max_lng, style, metadata, revision, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateMapZoneParams struct {
	TenantID uuid.UUID
	SiteID   uuid.UUID
	FloorID  *uuid.UUID
	Name     string
	Kind     string
	Geometry json.RawMessage
	MinLat   *float64
	MinLng   *float64
	MaxLat   *float64
	MaxLng   *float64
	Style    []byte
	Metadata []byte
	UserID   *uuid.UUID
}

func (q *Queries) CreateMapZone(ctx context.Context, arg CreateMapZoneParams) (MapZone, error) {
	row := q.db.QueryRow(ctx, createMapZone,
		arg.TenantID,
		arg.SiteID,
		arg.FloorID,
		arg.Name,
		arg.Kind,
		arg.Geometry,
		arg.MinLat,
		arg.MinLng,
		arg.MaxLat,
		arg.MaxLng,
		arg.Style,
		arg.Metadata,
		arg.UserID,
	)
	var i MapZone
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.FloorID,
		&i.Name,
		&i.Kind,
		&i.Geometry,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.Style,
		&i.Metadata,
		&i.Revision,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMapBuilding = `-- name: DeleteMapBuilding :one
UPDATE map_buildings
SET deleted_at = now(), revision = nextval('map_revision')
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, site_id, name, footprint, lat, lng, revision, created_at, updated_at, deleted_at
`

type DeleteMapBuildingParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteMapBuilding(ctx context.Context, arg DeleteMapBuildingParams) (MapBuilding, error) {
	row := q.db.QueryRow(ctx, deleteMapBuilding, arg.ID, arg.TenantID)
	var i MapBuilding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Footprint,
		&i.Lat,
		&i.Lng,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMapDevice = `-- name: DeleteMapDevice :exec
UPDATE map_devices
SET deleted_at = now()
WHERE id = $1 AND tenant_id = $2
`

type DeleteMapDeviceParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteMapDevice(ctx context.Context, arg DeleteMapDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteMapDevice, arg.ID, arg.TenantID)
	return err
}

const deleteMapFloor = `-- name: DeleteMapFloor :one
UPDATE map_floors
SET deleted_at = now(), revision = nextval('map_revision')
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, building_id, name, ordinal, plan_key, plan_content_type, plan_width_px, plan_height_px, georef, revision, created_at, updated_at, deleted_at
`

type DeleteMapFloorParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteMapFloor(ctx context.Context, arg DeleteMapFloorParams) (MapFloor, error) {
	row := q.db.QueryRow(ctx, deleteMapFloor, arg.ID, arg.TenantID)
	var i MapFloor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildingID,
		&i.Name,
		&i.Ordinal,
		&i.PlanKey,
		&i.PlanContentType,
		&i.PlanWidthPx,
		&i.PlanHeightPx,
		&i.Georef,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMapPlacement = `-- name: DeleteMapPlacement :exec
DELETE FROM map_placements
WHERE id = $1 AND ($2::uuid IS NULL OR tenant_id = $2)
`

type DeleteMapPlacementParams struct {
	ID       uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) DeleteMapPlacement(ctx context.Context, arg DeleteMapPlacementParams) error {
	_, err := q.db.Exec(ctx, deleteMapPlacement, arg.ID, arg.TenantID)
	return err
}

const deleteMapRegion = `-- name: DeleteMapRegion :exec
DELETE FROM map_regions
WHERE id = $1 AND tenant_id = $2
`

type DeleteMapRegionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteMapRegion(ctx context.Context, arg DeleteMapRegionParams) error {
	_, err := q.db.Exec(ctx, deleteMapRegion, arg.ID, arg.TenantID)
	return err
}

const deleteMapView = `-- name: DeleteMapView :exec
UPDATE map_views
SET deleted_at = now()
WHERE id = $1 AND tenant_id = $2 AND owner_id = $3
`

type DeleteMapViewParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	OwnerID  uuid.UUID
}

func (q *Queries) DeleteMapView(ctx context.Context, arg DeleteMapViewParams) error {
	_, err := q.db.Exec(ctx, deleteMapView, arg.ID, arg.TenantID, arg.OwnerID)
	return err
}

const deleteMapZone = `-- name: DeleteMapZone :exec
UPDATE map_zones
SET deleted_at = now(), revision = nextval('map_revision'), updated_by = $1
WHERE id = $2 AND ($3::uuid IS NULL OR tenant_id = $3)
`

type DeleteMapZoneParams struct {
	UserID   *uuid.UUID
	ID       uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) DeleteMapZone(ctx context.Context, arg DeleteMapZoneParams) error {
	_, err := q.db.Exec(ctx, deleteMapZone, arg.UserID, arg.ID, arg.TenantID)
	return err
}

const deletePlacementByEntity = `-- name: DeletePlacementByEntity :exec
DELETE FROM map_placements
WHERE entity_type = $1 AND entity_id = $2 AND tenant_id = $3
`

type DeletePlacementByEntityParams struct {
	EntityType string
	EntityID   uuid.UUID
	TenantID   uuid.UUID
}

func (q *Queries) DeletePlacementByEntity(ctx context.Context, arg DeletePlacementByEntityParams) error {
	_, err := q.db.Exec(ctx, deletePlacementByEntity, arg.EntityType, arg.EntityID, arg.TenantID)
	return err
}

const getMapBuilding = `-- name: GetMapBuilding :one
SELECT id, tenant_id, site_id, name, footprint, lat, lng, revision, created_at, updated_at, deleted_at FROM map_buildings
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetMapBuildingParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetMapBuilding(ctx context.Context, arg GetMapBuildingParams) (MapBuilding, error) {
	row := q.db.QueryRow(ctx, getMapBuilding, arg.ID, arg.TenantID)
	var i MapBuilding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Footprint,
		&i.Lat,
		&i.Lng,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMapBuildingOnSite = `-- name: GetMapBuildingOnSite :one
SELECT b.id, b.tenant_id, b.site_id, b.name, b.footprint, b.lat, b.lng, b.revision, b.created_at, b.updated_at, b.deleted_at FROM map_buildings b JOIN sites s ON s.id = b.site_id AND s.tenant_id = b.tenant_id
WHERE b.id = $1 AND b.tenant_id = $2 AND b.site_id = $3
AND b.deleted_at IS NULL AND s.deleted_at IS NULL
FOR UPDATE OF b
`

type GetMapBuildingOnSiteParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	SiteID   uuid.UUID
}

func (q *Queries) GetMapBuildingOnSite(ctx context.Context, arg GetMapBuildingOnSiteParams) (MapBuilding, error) {
	row := q.db.QueryRow(ctx, getMapBuildingOnSite, arg.ID, arg.TenantID, arg.SiteID)
	var i MapBuilding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Footprint,
		&i.Lat,
		&i.Lng,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMapDevice = `-- name: GetMapDevice :one
SELECT id, tenant_id, site_id, kind, name, status, props, created_at, updated_at, deleted_at FROM map_devices
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetMapDeviceParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetMapDevice(ctx context.Context, arg GetMapDeviceParams) (MapDevice, error) {
	row := q.db.QueryRow(ctx, getMapDevice, arg.ID, arg.TenantID)
	var i MapDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Props,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMapFloor = `-- name: GetMapFloor :one
SELECT id, tenant_id, building_id, name, ordinal, plan_key, plan_content_type, plan_width_px, plan_height_px, georef, revision, created_at, updated_at, deleted_at FROM map_floors
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetMapFloorParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetMapFloor(ctx context.Context, arg GetMapFloorParams) (MapFloor, error) {
	row := q.db.QueryRow(ctx, getMapFloor, arg.ID, arg.TenantID)
	var i MapFloor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildingID,
		&i.Name,
		&i.Ordinal,
		&i.PlanKey,
		&i.PlanContentType,
		&i.PlanWidthPx,
		&i.PlanHeightPx,
		&i.Georef,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMapFloorOnSite = `-- name: GetMapFloorOnSite :one
SELECT f.id, f.tenant_id, f.building_id, f.name, f.ordinal, f.plan_key, f.plan_content_type, f.plan_width_px, f.plan_height_px, f.georef, f.revision, f.created_at, f.updated_at, f.deleted_at FROM map_floors f
JOIN map_buildings b ON b.id=f.building_id AND b.tenant_id=f.tenant_id
JOIN sites s ON s.id=b.site_id AND s.tenant_id=b.tenant_id
WHERE f.id= $1 AND f.tenant_id= $2 AND b.site_id= $3
  AND f.deleted_at IS NULL AND b.deleted_at IS NULL AND s.deleted_at IS NULL
FOR SHARE OF f,b,s
`

type GetMapFloorOnSiteParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	SiteID   uuid.UUID
}

func (q *Queries) GetMapFloorOnSite(ctx context.Context, arg GetMapFloorOnSiteParams) (MapFloor, error) {
	row := q.db.QueryRow(ctx, getMapFloorOnSite, arg.ID, arg.TenantID, arg.SiteID)
	var i MapFloor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildingID,
		&i.Name,
		&i.Ordinal,
		&i.PlanKey,
		&i.PlanContentType,
		&i.PlanWidthPx,
		&i.PlanHeightPx,
		&i.Georef,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMapPlacement = `-- name: GetMapPlacement :one
SELECT id, tenant_id, site_id, entity_type, entity_id, floor_id, lat, lng, x, y, bearing_deg, fov_deg, range_m, props, revision, created_by, updated_by, created_at, updated_at FROM map_placements
WHERE id = $1 AND ($2::uuid IS NULL OR tenant_id = $2)
`

type GetMapPlacementParams struct {
	ID       uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) GetMapPlacement(ctx context.Context, arg GetMapPlacementParams) (MapPlacement, error) {
	row := q.db.QueryRow(ctx, getMapPlacement, arg.ID, arg.TenantID)
	var i MapPlacement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.EntityType,
		&i.EntityID,
		&i.FloorID,
		&i.Lat,
		&i.Lng,
		&i.X,
		&i.Y,
		&i.BearingDeg,
		&i.FovDeg,
		&i.RangeM,
		&i.Props,
		&i.Revision,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapPlacementByEntityFloor = `-- name: GetMapPlacementByEntityFloor :one
SELECT id, tenant_id, site_id, entity_type, entity_id, floor_id, lat, lng, x, y, bearing_deg, fov_deg, range_m, props, revision, created_by, updated_by, created_at, updated_at FROM map_placements
WHERE entity_type = $1 AND entity_id = $2 AND floor_id = $3 AND ($4::uuid IS NULL OR tenant_id = $4)
`

type GetMapPlacementByEntityFloorParams struct {
	EntityType string
	EntityID   uuid.UUID
	FloorID    *uuid.UUID
	TenantID   *uuid.UUID
}

func (q *Queries) GetMapPlacementByEntityFloor(ctx context.Context, arg GetMapPlacementByEntityFloorParams) (MapPlacement, error) {
	row := q.db.QueryRow(ctx, getMapPlacementByEntityFloor,
		arg.EntityType,
		arg.EntityID,
		arg.FloorID,
		arg.TenantID,
	)
	var i MapPlacement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.EntityType,
		&i.EntityID,
		&i.FloorID,
		&i.Lat,
		&i.Lng,
		&i.X,
		&i.Y,
		&i.BearingDeg,
		&i.FovDeg,
		&i.RangeM,
		&i.Props,
		&i.Revision,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapPlacementByEntityGeo = `-- name: GetMapPlacementByEntityGeo :one
SELECT id, tenant_id, site_id, entity_type, entity_id, floor_id, lat, lng, x, y, bearing_deg, fov_deg, range_m, props, revision, created_by, updated_by, created_at, updated_at FROM map_placements
WHERE entity_type = $1 AND entity_id = $2 AND floor_id IS NULL AND ($3::uuid IS NULL OR tenant_id = $3)
`

type GetMapPlacementByEntityGeoParams struct {
	EntityType string
	EntityID   uuid.UUID
	TenantID   *uuid.UUID
}

func (q *Queries) GetMapPlacementByEntityGeo(ctx context.Context, arg GetMapPlacementByEntityGeoParams) (MapPlacement, error) {
	row := q.db.QueryRow(ctx, getMapPlacementByEntityGeo, arg.EntityType, arg.EntityID, arg.TenantID)
	var i MapPlacement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.EntityType,
		&i.EntityID,
		&i.FloorID,
		&i.Lat,
		&i.Lng,
		&i.X,
		&i.Y,
		&i.BearingDeg,
		&i.FovDeg,
		&i.RangeM,
		&i.Props,
		&i.Revision,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapRegion = `-- name: GetMapRegion :one
SELECT id, tenant_id, parent_id, name, created_at FROM map_regions
WHERE id = $1 AND tenant_id = $2
`

type GetMapRegionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetMapRegion(ctx context.Context, arg GetMapRegionParams) (MapRegion, error) {
	row := q.db.QueryRow(ctx, getMapRegion, arg.ID, arg.TenantID)
	var i MapRegion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getMapSiteRevision = `-- name: GetMapSiteRevision :one
SELECT coalesce(max(revision), 0)::bigint AS revision
FROM map_placements
WHERE site_id = $1 AND ($2::uuid IS NULL OR tenant_id = $2)
`

type GetMapSiteRevisionParams struct {
	SiteID   uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) GetMapSiteRevision(ctx context.Context, arg GetMapSiteRevisionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMapSiteRevision, arg.SiteID, arg.TenantID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getMapUserPrefs = `-- name: GetMapUserPrefs :one
SELECT user_id, tenant_id, prefs, updated_at FROM map_user_prefs
WHERE user_id = $1
`

func (q *Queries) GetMapUserPrefs(ctx context.Context, userID uuid.UUID) (MapUserPref, error) {
	row := q.db.QueryRow(ctx, getMapUserPrefs, userID)
	var i MapUserPref
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.Prefs,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapView = `-- name: GetMapView :one
SELECT id, tenant_id, owner_id, name, shared, state, created_at, updated_at, deleted_at FROM map_views
WHERE id = $1 AND tenant_id = $2 AND (owner_id = $3 OR shared = true) AND deleted_at IS NULL
`

type GetMapViewParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	OwnerID  uuid.UUID
}

func (q *Queries) GetMapView(ctx context.Context, arg GetMapViewParams) (MapView, error) {
	row := q.db.QueryRow(ctx, getMapView, arg.ID, arg.TenantID, arg.OwnerID)
	var i MapView
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerID,
		&i.Name,
		&i.Shared,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMapZone = `-- name: GetMapZone :one
SELECT id, tenant_id, site_id, floor_id, name, kind, geometry, min_lat, min_lng, max_lat, max_lng, style, metadata, revision, created_by, updated_by, created_at, updated_at, deleted_at FROM map_zones
WHERE map_zones.id = $1::uuid AND ($2::uuid IS NULL OR map_zones.tenant_id = $2) AND map_zones.deleted_at IS NULL
AND EXISTS(SELECT 1 FROM sites s WHERE s.id = map_zones.site_id AND s.tenant_id = map_zones.tenant_id AND s.deleted_at IS NULL)
AND (map_zones.floor_id IS NULL OR EXISTS(SELECT 1 FROM map_floors f JOIN map_buildings b ON b.id = f.building_id AND b.tenant_id = f.tenant_id
 WHERE f.id = map_zones.floor_id AND f.tenant_id = map_zones.tenant_id AND b.site_id = map_zones.site_id AND f.deleted_at IS NULL AND b.deleted_at IS NULL))
`

type GetMapZoneParams struct {
	ID       uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) GetMapZone(ctx context.Context, arg GetMapZoneParams) (MapZone, error) {
	row := q.db.QueryRow(ctx, getMapZone, arg.ID, arg.TenantID)
	var i MapZone
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.FloorID,
		&i.Name,
		&i.Kind,
		&i.Geometry,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.Style,
		&i.Metadata,
		&i.Revision,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSiteGeo = `-- name: GetSiteGeo :one
SELECT id, tenant_id, name, lat, lng, default_zoom, region_id
FROM sites
WHERE id = $1 AND ($2::uuid IS NULL OR tenant_id = $2) AND deleted_at IS NULL
`

type GetSiteGeoParams struct {
	ID       uuid.UUID
	TenantID *uuid.UUID
}

type GetSiteGeoRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Lat         *float64
	Lng         *float64
	DefaultZoom *float32
	RegionID    *uuid.UUID
}

func (q *Queries) GetSiteGeo(ctx context.Context, arg GetSiteGeoParams) (GetSiteGeoRow, error) {
	row := q.db.QueryRow(ctx, getSiteGeo, arg.ID, arg.TenantID)
	var i GetSiteGeoRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Lat,
		&i.Lng,
		&i.DefaultZoom,
		&i.RegionID,
	)
	return i, err
}

const listMapBuildingsBySite = `-- name: ListMapBuildingsBySite :many
SELECT id, tenant_id, site_id, name, footprint, lat, lng, revision, created_at, updated_at, deleted_at FROM map_buildings
WHERE site_id = $1 AND ($2::uuid IS NULL OR tenant_id = $2) AND deleted_at IS NULL
ORDER BY name ASC
`

type ListMapBuildingsBySiteParams struct {
	SiteID   uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) ListMapBuildingsBySite(ctx context.Context, arg ListMapBuildingsBySiteParams) ([]MapBuilding, error) {
	rows, err := q.db.Query(ctx, listMapBuildingsBySite, arg.SiteID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapBuilding{}
	for rows.Next() {
		var i MapBuilding
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Name,
			&i.Footprint,
			&i.Lat,
			&i.Lng,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapDevicesBySite = `-- name: ListMapDevicesBySite :many
SELECT id, tenant_id, site_id, kind, name, status, props, created_at, updated_at, deleted_at FROM map_devices
WHERE site_id = $1 AND tenant_id = $2 AND deleted_at IS NULL
ORDER BY name ASC
`

type ListMapDevicesBySiteParams struct {
	SiteID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) ListMapDevicesBySite(ctx context.Context, arg ListMapDevicesBySiteParams) ([]MapDevice, error) {
	rows, err := q.db.Query(ctx, listMapDevicesBySite, arg.SiteID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapDevice{}
	for rows.Next() {
		var i MapDevice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.Kind,
			&i.Name,
			&i.Status,
			&i.Props,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapFloorsByBuilding = `-- name: ListMapFloorsByBuilding :many
SELECT id, tenant_id, building_id, name, ordinal, plan_key, plan_content_type, plan_width_px, plan_height_px, georef, revision, created_at, updated_at, deleted_at FROM map_floors
WHERE building_id = $1 AND tenant_id = $2 AND deleted_at IS NULL
ORDER BY ordinal ASC
`

type ListMapFloorsByBuildingParams struct {
	BuildingID uuid.UUID
	TenantID   uuid.UUID
}

func (q *Queries) ListMapFloorsByBuilding(ctx context.Context, arg ListMapFloorsByBuildingParams) ([]MapFloor, error) {
	rows, err := q.db.Query(ctx, listMapFloorsByBuilding, arg.BuildingID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapFloor{}
	for rows.Next() {
		var i MapFloor
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BuildingID,
			&i.Name,
			&i.Ordinal,
			&i.PlanKey,
			&i.PlanContentType,
			&i.PlanWidthPx,
			&i.PlanHeightPx,
			&i.Georef,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapFloorsBySite = `-- name: ListMapFloorsBySite :many
SELECT f.id, f.tenant_id, f.building_id, f.name, f.ordinal, f.plan_key, f.plan_content_type, f.plan_width_px, f.plan_height_px, f.georef, f.revision, f.created_at, f.updated_at, f.deleted_at
FROM map_floors f
JOIN map_buildings b ON b.id = f.building_id AND b.tenant_id = f.tenant_id
WHERE b.site_id = $1 AND ($2::uuid IS NULL OR f.tenant_id = $2) AND f.deleted_at IS NULL AND b.deleted_at IS NULL
ORDER BY f.building_id ASC, f.ordinal ASC
`

type ListMapFloorsBySiteParams struct {
	SiteID   uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) ListMapFloorsBySite(ctx context.Context, arg ListMapFloorsBySiteParams) ([]MapFloor, error) {
	rows, err := q.db.Query(ctx, listMapFloorsBySite, arg.SiteID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapFloor{}
	for rows.Next() {
		var i MapFloor
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BuildingID,
			&i.Name,
			&i.Ordinal,
			&i.PlanKey,
			&i.PlanContentType,
			&i.PlanWidthPx,
			&i.PlanHeightPx,
			&i.Georef,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapPlacementsByFloor = `-- name: ListMapPlacementsByFloor :many
SELECT id, tenant_id, site_id, entity_type, entity_id, floor_id, lat, lng, x, y, bearing_deg, fov_deg, range_m, props, revision, created_by, updated_by, created_at, updated_at FROM map_placements
WHERE floor_id = $1 AND tenant_id = $2
`

type ListMapPlacementsByFloorParams struct {
	FloorID  *uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) ListMapPlacementsByFloor(ctx context.Context, arg ListMapPlacementsByFloorParams) ([]MapPlacement, error) {
	rows, err := q.db.Query(ctx, listMapPlacementsByFloor, arg.FloorID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapPlacement{}
	for rows.Next() {
		var i MapPlacement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.EntityType,
			&i.EntityID,
			&i.FloorID,
			&i.Lat,
			&i.Lng,
			&i.X,
			&i.Y,
			&i.BearingDeg,
			&i.FovDeg,
			&i.RangeM,
			&i.Props,
			&i.Revision,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapPlacementsBySite = `-- name: ListMapPlacementsBySite :many
SELECT id, tenant_id, site_id, entity_type, entity_id, floor_id, lat, lng, x, y, bearing_deg, fov_deg, range_m, props, revision, created_by, updated_by, created_at, updated_at FROM map_placements
WHERE site_id = $1 AND tenant_id = $2
`

type ListMapPlacementsBySiteParams struct {
	SiteID   uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) ListMapPlacementsBySite(ctx context.Context, arg ListMapPlacementsBySiteParams) ([]MapPlacement, error) {
	rows, err := q.db.Query(ctx, listMapPlacementsBySite, arg.SiteID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapPlacement{}
	for rows.Next() {
		var i MapPlacement
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.EntityType,
			&i.EntityID,
			&i.FloorID,
			&i.Lat,
			&i.Lng,
			&i.X,
			&i.Y,
			&i.BearingDeg,
			&i.FovDeg,
			&i.RangeM,
			&i.Props,
			&i.Revision,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapPlacementsDetailed = `-- name: ListMapPlacementsDetailed :many
SELECT
    p.id,
    p.tenant_id,
    p.site_id,
    p.entity_type,
    p.entity_id,
    p.floor_id,
    p.lat,
    p.lng,
    p.x,
    p.y,
    p.bearing_deg,
    p.fov_deg,
    p.range_m,
    p.props,
    p.revision,
    c.display_name AS camera_name,
    c.server_id AS camera_server_id,
    c.status AS camera_status,
    c.lpr AS camera_lpr,
    fs.name AS server_name,
    fs.status AS server_status,
    md.name AS device_name,
    md.kind AS device_kind,
    md.status AS device_status,
    coalesce(
        CASE WHEN p.entity_type = 'camera' THEN
            (SELECT count(*)::int
             FROM alarms a
             WHERE ($1::uuid IS NULL OR a.tenant_id = p.tenant_id)
               AND a.site_id = p.site_id
               AND a.camera_id = p.entity_id
               AND a.status = ANY(ARRAY['open', 'acknowledged', 'assigned', 'investigating']))
        ELSE 0 END,
        0
    )::int AS alarm_count
FROM map_placements p
LEFT JOIN cameras c ON c.id = p.entity_id AND p.entity_type = 'camera' AND c.tenant_id = p.tenant_id AND c.deleted_at IS NULL
LEFT JOIN frigate_servers fs ON fs.id = p.entity_id AND p.entity_type = 'server' AND fs.tenant_id = p.tenant_id AND fs.deleted_at IS NULL
LEFT JOIN map_devices md ON md.id = p.entity_id AND p.entity_type = 'device' AND md.tenant_id = p.tenant_id AND md.deleted_at IS NULL
WHERE p.site_id = $2
  AND ($1::uuid IS NULL OR p.tenant_id = $1)
  AND ($3::uuid IS NULL OR p.floor_id = $3)
  AND ($4::boolean IS NULL OR ($4 = true AND p.floor_id IS NULL) OR ($4 = false AND p.floor_id IS NOT NULL))
  AND (
      $5::double precision IS NULL
      OR (p.lat >= $5 AND p.lat <= $6 AND p.lng >= $7 AND p.lng <= $8)
  )
  AND (p.floor_id IS NULL OR EXISTS (
      SELECT 1 FROM map_floors f JOIN map_buildings b ON b.id=f.building_id AND b.tenant_id=f.tenant_id
      WHERE f.id=p.floor_id AND f.tenant_id=p.tenant_id AND b.site_id=p.site_id
        AND f.deleted_at IS NULL AND b.deleted_at IS NULL))
  AND (
      (p.entity_type = 'camera' AND c.id IS NOT NULL)
      OR (p.entity_type = 'server' AND fs.id IS NOT NULL)
      OR (p.entity_type = 'device' AND md.id IS NOT NULL)
  )
ORDER BY p.revision ASC
`

type ListMapPlacementsDetailedParams struct {
	TenantID *uuid.UUID
	SiteID   uuid.UUID
	FloorID  *uuid.UUID
	IsGeo    *bool
	MinLat   *float64
	MaxLat   *float64
	MinLng   *float64
	MaxLng   *float64
}

type ListMapPlacementsDetailedRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SiteID         uuid.UUID
	EntityType     string
	EntityID       uuid.UUID
	FloorID        *uuid.UUID
	Lat            *float64
	Lng            *float64
	X              *float32
	Y              *float32
	BearingDeg     *float32
	FovDeg         *float32
	RangeM         *float32
	Props          json.RawMessage
	Revision       int64
	CameraName     *string
	CameraServerID *uuid.UUID
	CameraStatus   *string
	CameraLpr      *bool
	ServerName     *string
	ServerStatus   *string
	DeviceName     *string
	DeviceKind     *string
	DeviceStatus   *string
	AlarmCount     int32
}

func (q *Queries) ListMapPlacementsDetailed(ctx context.Context, arg ListMapPlacementsDetailedParams) ([]ListMapPlacementsDetailedRow, error) {
	rows, err := q.db.Query(ctx, listMapPlacementsDetailed,
		arg.TenantID,
		arg.SiteID,
		arg.FloorID,
		arg.IsGeo,
		arg.MinLat,
		arg.MaxLat,
		arg.MinLng,
		arg.MaxLng,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMapPlacementsDetailedRow{}
	for rows.Next() {
		var i ListMapPlacementsDetailedRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.EntityType,
			&i.EntityID,
			&i.FloorID,
			&i.Lat,
			&i.Lng,
			&i.X,
			&i.Y,
			&i.BearingDeg,
			&i.FovDeg,
			&i.RangeM,
			&i.Props,
			&i.Revision,
			&i.CameraName,
			&i.CameraServerID,
			&i.CameraStatus,
			&i.CameraLpr,
			&i.ServerName,
			&i.ServerStatus,
			&i.DeviceName,
			&i.DeviceKind,
			&i.DeviceStatus,
			&i.AlarmCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapRegions = `-- name: ListMapRegions :many
SELECT id, tenant_id, parent_id, name, created_at FROM map_regions
WHERE tenant_id = $1
ORDER BY name ASC
`

func (q *Queries) ListMapRegions(ctx context.Context, tenantID uuid.UUID) ([]MapRegion, error) {
	rows, err := q.db.Query(ctx, listMapRegions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapRegion{}
	for rows.Next() {
		var i MapRegion
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapSiteOverviews = `-- name: ListMapSiteOverviews :many
SELECT
    s.id,
    s.tenant_id,
    s.name,
    s.lat,
    s.lng,
    s.default_zoom,
    s.region_id,
    r.name AS region_name,
    coalesce(count(DISTINCT c.id) FILTER (WHERE c.deleted_at IS NULL), 0)::int AS camera_count,
    coalesce(count(DISTINCT c.id) FILTER (WHERE c.deleted_at IS NULL AND c.status = 'online'), 0)::int AS online_cameras,
    coalesce(count(DISTINCT c.id) FILTER (WHERE c.deleted_at IS NULL AND c.status = 'offline'), 0)::int AS offline_cameras,
    coalesce(count(DISTINCT c.id) FILTER (WHERE c.deleted_at IS NULL AND c.status = 'degraded'), 0)::int AS degraded_cameras,
    coalesce(count(DISTINCT a.id) FILTER (WHERE a.status = ANY(ARRAY['open', 'acknowledged', 'assigned', 'investigating'])), 0)::int AS alarm_count
FROM sites s
LEFT JOIN map_regions r ON r.id = s.region_id AND ($1::uuid IS NULL OR r.tenant_id = s.tenant_id)
LEFT JOIN cameras c ON c.site_id = s.id AND ($1::uuid IS NULL OR c.tenant_id = s.tenant_id) AND ($2::uuid[] IS NULL OR c.id = ANY($2::uuid[]))
LEFT JOIN alarms a ON a.site_id = s.id AND ($1::uuid IS NULL OR a.tenant_id = s.tenant_id) AND ($2::uuid[] IS NULL OR a.camera_id = ANY($2::uuid[]))
WHERE ($1::uuid IS NULL OR s.tenant_id = $1)
  AND s.deleted_at IS NULL
  AND s.id = ANY($3::uuid[])
GROUP BY s.id, s.tenant_id, s.name, s.lat, s.lng, s.default_zoom, s.region_id, r.name
ORDER BY s.name ASC
`

type ListMapSiteOverviewsParams struct {
	TenantID  *uuid.UUID
	CameraIds []uuid.UUID
	SiteIds   []uuid.UUID
}

type ListMapSiteOverviewsRow struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	Name            string
	Lat             *float64
	Lng             *float64
	DefaultZoom     *float32
	RegionID        *uuid.UUID
	RegionName      *string
	CameraCount     int32
	OnlineCameras   int32
	OfflineCameras  int32
	DegradedCameras int32
	AlarmCount      int32
}

func (q *Queries) ListMapSiteOverviews(ctx context.Context, arg ListMapSiteOverviewsParams) ([]ListMapSiteOverviewsRow, error) {
	rows, err := q.db.Query(ctx, listMapSiteOverviews, arg.TenantID, arg.CameraIds, arg.SiteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMapSiteOverviewsRow{}
	for rows.Next() {
		var i ListMapSiteOverviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.DefaultZoom,
			&i.RegionID,
			&i.RegionName,
			&i.CameraCount,
			&i.OnlineCameras,
			&i.OfflineCameras,
			&i.DegradedCameras,
			&i.AlarmCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapViews = `-- name: ListMapViews :many
SELECT id, tenant_id, owner_id, name, shared, state, created_at, updated_at, deleted_at FROM map_views
WHERE tenant_id = $1 AND (owner_id = $2 OR shared = true) AND deleted_at IS NULL
ORDER BY name ASC
`

type ListMapViewsParams struct {
	TenantID uuid.UUID
	OwnerID  uuid.UUID
}

func (q *Queries) ListMapViews(ctx context.Context, arg ListMapViewsParams) ([]MapView, error) {
	rows, err := q.db.Query(ctx, listMapViews, arg.TenantID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapView{}
	for rows.Next() {
		var i MapView
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OwnerID,
			&i.Name,
			&i.Shared,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapZonesBySite = `-- name: ListMapZonesBySite :many
SELECT id, tenant_id, site_id, floor_id, name, kind, geometry, min_lat, min_lng, max_lat, max_lng, style, metadata, revision, created_by, updated_by, created_at, updated_at, deleted_at FROM map_zones
WHERE map_zones.site_id = $1::uuid AND ($2::uuid IS NULL OR map_zones.tenant_id = $2) AND map_zones.deleted_at IS NULL
AND EXISTS(SELECT 1 FROM sites s WHERE s.id = map_zones.site_id AND s.tenant_id = map_zones.tenant_id AND s.deleted_at IS NULL)
AND (map_zones.floor_id IS NULL OR EXISTS(SELECT 1 FROM map_floors f JOIN map_buildings b ON b.id = f.building_id AND b.tenant_id = f.tenant_id
 WHERE f.id = map_zones.floor_id AND f.tenant_id = map_zones.tenant_id AND b.site_id = map_zones.site_id AND f.deleted_at IS NULL AND b.deleted_at IS NULL))
ORDER BY name ASC
`

type ListMapZonesBySiteParams struct {
	SiteID   uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) ListMapZonesBySite(ctx context.Context, arg ListMapZonesBySiteParams) ([]MapZone, error) {
	rows, err := q.db.Query(ctx, listMapZonesBySite, arg.SiteID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapZone{}
	for rows.Next() {
		var i MapZone
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SiteID,
			&i.FloorID,
			&i.Name,
			&i.Kind,
			&i.Geometry,
			&i.MinLat,
			&i.MinLng,
			&i.MaxLat,
			&i.MaxLng,
			&i.Style,
			&i.Metadata,
			&i.Revision,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteCamerasForImport = `-- name: ListSiteCamerasForImport :many
SELECT c.id, c.display_name, c.remote_name
FROM cameras c
WHERE c.site_id = $1
  AND ($2::uuid IS NULL OR c.tenant_id = $2)
  AND c.deleted_at IS NULL
ORDER BY c.id
`

type ListSiteCamerasForImportParams struct {
	SiteID   uuid.UUID
	TenantID *uuid.UUID
}

type ListSiteCamerasForImportRow struct {
	ID          uuid.UUID
	DisplayName string
	RemoteName  string
}

func (q *Queries) ListSiteCamerasForImport(ctx context.Context, arg ListSiteCamerasForImportParams) ([]ListSiteCamerasForImportRow, error) {
	rows, err := q.db.Query(ctx, listSiteCamerasForImport, arg.SiteID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteCamerasForImportRow{}
	for rows.Next() {
		var i ListSiteCamerasForImportRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.RemoteName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSitesGeo = `-- name: ListSitesGeo :many
SELECT id, tenant_id, name, lat, lng, default_zoom, region_id
FROM sites
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

type ListSitesGeoRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Lat         *float64
	Lng         *float64
	DefaultZoom *float32
	RegionID    *uuid.UUID
}

func (q *Queries) ListSitesGeo(ctx context.Context, tenantID uuid.UUID) ([]ListSitesGeoRow, error) {
	rows, err := q.db.Query(ctx, listSitesGeo, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesGeoRow{}
	for rows.Next() {
		var i ListSitesGeoRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.DefaultZoom,
			&i.RegionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnplacedCamerasBySite = `-- name: ListUnplacedCamerasBySite :many
SELECT c.id, c.display_name, c.remote_name, c.site_id, c.status
FROM cameras c
WHERE c.site_id = $1
  AND ($2::uuid IS NULL OR c.tenant_id = $2)
  AND c.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM map_placements p
      WHERE p.entity_type = 'camera' AND p.entity_id = c.id AND p.tenant_id = c.tenant_id AND p.site_id = c.site_id
        AND (($3::uuid IS NULL AND p.floor_id IS NULL) OR p.floor_id = $3)
  )
ORDER BY c.display_name ASC
`

type ListUnplacedCamerasBySiteParams struct {
	SiteID   uuid.UUID
	TenantID *uuid.UUID
	FloorID  *uuid.UUID
}

type ListUnplacedCamerasBySiteRow struct {
	ID          uuid.UUID
	DisplayName string
	RemoteName  string
	SiteID      uuid.UUID
	Status      string
}

func (q *Queries) ListUnplacedCamerasBySite(ctx context.Context, arg ListUnplacedCamerasBySiteParams) ([]ListUnplacedCamerasBySiteRow, error) {
	rows, err := q.db.Query(ctx, listUnplacedCamerasBySite, arg.SiteID, arg.TenantID, arg.FloorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnplacedCamerasBySiteRow{}
	for rows.Next() {
		var i ListUnplacedCamerasBySiteRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.RemoteName,
			&i.SiteID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMapFloorOnSite = `-- name: LockMapFloorOnSite :one
SELECT f.id, f.tenant_id, f.building_id, f.name, f.ordinal, f.plan_key, f.plan_content_type, f.plan_width_px, f.plan_height_px, f.georef, f.revision, f.created_at, f.updated_at, f.deleted_at FROM map_floors f JOIN map_buildings b ON b.id = f.building_id AND b.tenant_id = f.tenant_id
JOIN sites s ON s.id = b.site_id AND s.tenant_id = b.tenant_id
WHERE f.id = $1 AND f.tenant_id = $2 AND b.site_id = $3
AND f.deleted_at IS NULL AND b.deleted_at IS NULL AND s.deleted_at IS NULL
FOR UPDATE OF f FOR SHARE OF b,s
`

type LockMapFloorOnSiteParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	SiteID   uuid.UUID
}

func (q *Queries) LockMapFloorOnSite(ctx context.Context, arg LockMapFloorOnSiteParams) (MapFloor, error) {
	row := q.db.QueryRow(ctx, lockMapFloorOnSite, arg.ID, arg.TenantID, arg.SiteID)
	var i MapFloor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildingID,
		&i.Name,
		&i.Ordinal,
		&i.PlanKey,
		&i.PlanContentType,
		&i.PlanWidthPx,
		&i.PlanHeightPx,
		&i.Georef,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const mapFloorHasContent = `-- name: MapFloorHasContent :one
SELECT (EXISTS(SELECT 1 FROM map_placements p WHERE p.floor_id = $1::uuid AND p.tenant_id = $2::uuid)
 OR EXISTS(SELECT 1 FROM map_zones z WHERE z.floor_id = $1::uuid AND z.tenant_id = $2::uuid AND z.deleted_at IS NULL))::boolean AS has_content
`

type MapFloorHasContentParams struct {
	FloorID  uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) MapFloorHasContent(ctx context.Context, arg MapFloorHasContentParams) (bool, error) {
	row := q.db.QueryRow(ctx, mapFloorHasContent, arg.FloorID, arg.TenantID)
	var has_content bool
	err := row.Scan(&has_content)
	return has_content, err
}

const updateMapBuilding = `-- name: UpdateMapBuilding :one
UPDATE map_buildings
SET name = coalesce($1, name),
    footprint = coalesce($2, footprint),
    lat = coalesce($3, lat),
    lng = coalesce($4, lng),
    revision = nextval('map_revision'),
    updated_at = now()
WHERE id = $5 AND tenant_id = $6 AND deleted_at IS NULL
RETURNING id, tenant_id, site_id, name, footprint, lat, lng, revision, created_at, updated_at, deleted_at
`

type UpdateMapBuildingParams struct {
	Name      *string
	Footprint []byte
	Lat       *float64
	Lng       *float64
	ID        uuid.UUID
	TenantID  uuid.UUID
}

func (q *Queries) UpdateMapBuilding(ctx context.Context, arg UpdateMapBuildingParams) (MapBuilding, error) {
	row := q.db.QueryRow(ctx, updateMapBuilding,
		arg.Name,
		arg.Footprint,
		arg.Lat,
		arg.Lng,
		arg.ID,
		arg.TenantID,
	)
	var i MapBuilding
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Name,
		&i.Footprint,
		&i.Lat,
		&i.Lng,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMapDevice = `-- name: UpdateMapDevice :one
UPDATE map_devices
SET name = coalesce($1, name),
    kind = coalesce($2, kind),
    status = coalesce($3, status),
    props = coalesce($4, props),
    updated_at = now()
WHERE id = $5 AND tenant_id = $6 AND deleted_at IS NULL
RETURNING id, tenant_id, site_id, kind, name, status, props, created_at, updated_at, deleted_at
`

type UpdateMapDeviceParams struct {
	Name     *string
	Kind     *string
	Status   *string
	Props    []byte
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) UpdateMapDevice(ctx context.Context, arg UpdateMapDeviceParams) (MapDevice, error) {
	row := q.db.QueryRow(ctx, updateMapDevice,
		arg.Name,
		arg.Kind,
		arg.Status,
		arg.Props,
		arg.ID,
		arg.TenantID,
	)
	var i MapDevice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.Kind,
		&i.Name,
		&i.Status,
		&i.Props,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMapFloor = `-- name: UpdateMapFloor :one
UPDATE map_floors
SET name = coalesce($1, name),
    ordinal = coalesce($2, ordinal),
    plan_key = coalesce($3, plan_key),
    plan_content_type = coalesce($4, plan_content_type),
    plan_width_px = coalesce($5, plan_width_px),
    plan_height_px = coalesce($6, plan_height_px),
    georef = coalesce($7, georef),
    revision = nextval('map_revision'),
    updated_at = now()
WHERE id = $8 AND tenant_id = $9 AND deleted_at IS NULL
RETURNING id, tenant_id, building_id, name, ordinal, plan_key, plan_content_type, plan_width_px, plan_height_px, georef, revision, created_at, updated_at, deleted_at
`

type UpdateMapFloorParams struct {
	Name            *string
	Ordinal         *int32
	PlanKey         *string
	PlanContentType *string
	PlanWidthPx     *int32
	PlanHeightPx    *int32
	Georef          []byte
	ID              uuid.UUID
	TenantID        uuid.UUID
}

func (q *Queries) UpdateMapFloor(ctx context.Context, arg UpdateMapFloorParams) (MapFloor, error) {
	row := q.db.QueryRow(ctx, updateMapFloor,
		arg.Name,
		arg.Ordinal,
		arg.PlanKey,
		arg.PlanContentType,
		arg.PlanWidthPx,
		arg.PlanHeightPx,
		arg.Georef,
		arg.ID,
		arg.TenantID,
	)
	var i MapFloor
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BuildingID,
		&i.Name,
		&i.Ordinal,
		&i.PlanKey,
		&i.PlanContentType,
		&i.PlanWidthPx,
		&i.PlanHeightPx,
		&i.Georef,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMapZone = `-- name: UpdateMapZone :one
UPDATE map_zones
SET name = coalesce($1, name),
    kind = coalesce($2, kind),
    geometry = coalesce($3, geometry),
    floor_id = coalesce($4, floor_id),
    min_lat = coalesce($5, min_lat),
    min_lng = coalesce($6, min_lng),
    max_lat = coalesce($7, max_lat),
    max_lng = coalesce($8, max_lng),
    style = coalesce($9, style),
    metadata = coalesce($10, metadata),
    revision = nextval('map_revision'),
    updated_by = $11,
    updated_at = now()
WHERE id = $12 AND ($13::uuid IS NULL OR tenant_id = $13) AND deleted_at IS NULL
RETURNING id, tenant_id, site_id, floor_id, name, kind, geometry, min_lat, min_lng, max_lat, max_lng, style, metadata, revision, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateMapZoneParams struct {
	Name     *string
	Kind     *string
	Geometry []byte
	FloorID  *uuid.UUID
	MinLat   *float64
	MinLng   *float64
	MaxLat   *float64
	MaxLng   *float64
	Style    []byte
	Metadata []byte
	UserID   *uuid.UUID
	ID       uuid.UUID
	TenantID *uuid.UUID
}

func (q *Queries) UpdateMapZone(ctx context.Context, arg UpdateMapZoneParams) (MapZone, error) {
	row := q.db.QueryRow(ctx, updateMapZone,
		arg.Name,
		arg.Kind,
		arg.Geometry,
		arg.FloorID,
		arg.MinLat,
		arg.MinLng,
		arg.MaxLat,
		arg.MaxLng,
		arg.Style,
		arg.Metadata,
		arg.UserID,
		arg.ID,
		arg.TenantID,
	)
	var i MapZone
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.FloorID,
		&i.Name,
		&i.Kind,
		&i.Geometry,
		&i.MinLat,
		&i.MinLng,
		&i.MaxLat,
		&i.MaxLng,
		&i.Style,
		&i.Metadata,
		&i.Revision,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSiteGeo = `-- name: UpdateSiteGeo :one
UPDATE sites
SET lat = coalesce($1, lat),
    lng = coalesce($2, lng),
    default_zoom = coalesce($3, default_zoom),
    region_id = coalesce($4, region_id),
    updated_at = now()
WHERE id = $5 AND ($6::uuid IS NULL OR tenant_id = $6) AND deleted_at IS NULL
RETURNING id, tenant_id, name, lat, lng, default_zoom, region_id, updated_at
`

type UpdateSiteGeoParams struct {
	Lat         *float64
	Lng         *float64
	DefaultZoom *float32
	RegionID    *uuid.UUID
	ID          uuid.UUID
	TenantID    *uuid.UUID
}

type UpdateSiteGeoRow struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Lat         *float64
	Lng         *float64
	DefaultZoom *float32
	RegionID    *uuid.UUID
	UpdatedAt   time.Time
}

func (q *Queries) UpdateSiteGeo(ctx context.Context, arg UpdateSiteGeoParams) (UpdateSiteGeoRow, error) {
	row := q.db.QueryRow(ctx, updateSiteGeo,
		arg.Lat,
		arg.Lng,
		arg.DefaultZoom,
		arg.RegionID,
		arg.ID,
		arg.TenantID,
	)
	var i UpdateSiteGeoRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Lat,
		&i.Lng,
		&i.DefaultZoom,
		&i.RegionID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFloorPlacement = `-- name: UpsertFloorPlacement :one
INSERT INTO map_placements (
    tenant_id, site_id, entity_type, entity_id, floor_id,
    x, y, bearing_deg, fov_deg, range_m, props,
    revision, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    nextval('map_revision'), $12, $12
)
ON CONFLICT (entity_type, entity_id, floor_id) WHERE floor_id IS NOT NULL
DO UPDATE SET
    site_id = EXCLUDED.site_id,
    x = EXCLUDED.x,
    y = EXCLUDED.y,
    bearing_deg = EXCLUDED.bearing_deg,
    fov_deg = EXCLUDED.fov_deg,
    range_m = EXCLUDED.range_m,
    props = EXCLUDED.props,
    revision = EXCLUDED.revision,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, tenant_id, site_id, entity_type, entity_id, floor_id, lat, lng, x, y, bearing_deg, fov_deg, range_m, props, revision, created_by, updated_by, created_at, updated_at
`

type UpsertFloorPlacementParams struct {
	TenantID   uuid.UUID
	SiteID     uuid.UUID
	EntityType string
	EntityID   uuid.UUID
	FloorID    *uuid.UUID
	X          *float32
	Y          *float32
	BearingDeg *float32
	FovDeg     *float32
	RangeM     *float32
	Props      json.RawMessage
	UserID     *uuid.UUID
}

func (q *Queries) UpsertFloorPlacement(ctx context.Context, arg UpsertFloorPlacementParams) (MapPlacement, error) {
	row := q.db.QueryRow(ctx, upsertFloorPlacement,
		arg.TenantID,
		arg.SiteID,
		arg.EntityType,
		arg.EntityID,
		arg.FloorID,
		arg.X,
		arg.Y,
		arg.BearingDeg,
		arg.FovDeg,
		arg.RangeM,
		arg.Props,
		arg.UserID,
	)
	var i MapPlacement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.EntityType,
		&i.EntityID,
		&i.FloorID,
		&i.Lat,
		&i.Lng,
		&i.X,
		&i.Y,
		&i.BearingDeg,
		&i.FovDeg,
		&i.RangeM,
		&i.Props,
		&i.Revision,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGeoPlacement = `-- name: UpsertGeoPlacement :one
INSERT INTO map_placements (
    tenant_id, site_id, entity_type, entity_id, floor_id,
    lat, lng, bearing_deg, fov_deg, range_m, props,
    revision, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, NULL,
    $5, $6, $7, $8, $9, $10,
    nextval('map_revision'), $11, $11
)
ON CONFLICT (entity_type, entity_id) WHERE floor_id IS NULL
DO UPDATE SET
    site_id = EXCLUDED.site_id,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    bearing_deg = EXCLUDED.bearing_deg,
    fov_deg = EXCLUDED.fov_deg,
    range_m = EXCLUDED.range_m,
    props = EXCLUDED.props,
    revision = EXCLUDED.revision,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, tenant_id, site_id, entity_type, entity_id, floor_id, lat, lng, x, y, bearing_deg, fov_deg, range_m, props, revision, created_by, updated_by, created_at, updated_at
`

type UpsertGeoPlacementParams struct {
	TenantID   uuid.UUID
	SiteID     uuid.UUID
	EntityType string
	EntityID   uuid.UUID
	Lat        *float64
	Lng        *float64
	BearingDeg *float32
	FovDeg     *float32
	RangeM     *float32
	Props      json.RawMessage
	UserID     *uuid.UUID
}

func (q *Queries) UpsertGeoPlacement(ctx context.Context, arg UpsertGeoPlacementParams) (MapPlacement, error) {
	row := q.db.QueryRow(ctx, upsertGeoPlacement,
		arg.TenantID,
		arg.SiteID,
		arg.EntityType,
		arg.EntityID,
		arg.Lat,
		arg.Lng,
		arg.BearingDeg,
		arg.FovDeg,
		arg.RangeM,
		arg.Props,
		arg.UserID,
	)
	var i MapPlacement
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SiteID,
		&i.EntityType,
		&i.EntityID,
		&i.FloorID,
		&i.Lat,
		&i.Lng,
		&i.X,
		&i.Y,
		&i.BearingDeg,
		&i.FovDeg,
		&i.RangeM,
		&i.Props,
		&i.Revision,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMapUserPrefs = `-- name: UpsertMapUserPrefs :one
INSERT INTO map_user_prefs (user_id, tenant_id, prefs, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id)
DO UPDATE SET prefs = EXCLUDED.prefs, tenant_id = EXCLUDED.tenant_id, updated_at = now()
RETURNING user_id, tenant_id, prefs, updated_at
`

type UpsertMapUserPrefsParams struct {
	UserID   uuid.UUID
	TenantID *uuid.UUID
	Prefs    json.RawMessage
}

func (q *Queries) UpsertMapUserPrefs(ctx context.Context, arg UpsertMapUserPrefsParams) (MapUserPref, error) {
	row := q.db.QueryRow(ctx, upsertMapUserPrefs, arg.UserID, arg.TenantID, arg.Prefs)
	var i MapUserPref
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.Prefs,
		&i.UpdatedAt,
	)
	return i, err
}
