// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Alarm struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SiteID         uuid.UUID
	CameraID       uuid.UUID
	EventID        uuid.UUID
	Source         string
	Status         string
	AssignedTo     *uuid.UUID
	AcknowledgedBy *uuid.UUID
	AcknowledgedAt *time.Time
	ResolvedBy     *uuid.UUID
	ResolvedAt     *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AlarmSetting struct {
	Singleton bool
	EnabledAt time.Time
}

type ApiToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	TokenHash  []byte
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	RevokedAt  *time.Time
	LastUsedAt *time.Time
}

type AuditLog struct {
	ID         int64
	OccurredAt time.Time
	TenantID   *uuid.UUID
	ActorID    *uuid.UUID
	ActorName  string
	Action     string
	TargetType string
	TargetID   *uuid.UUID
	RequestID  string
	Ip         *netip.Addr
	Details    json.RawMessage
}

type Camera struct {
	ID                 uuid.UUID
	TenantID           uuid.UUID
	SiteID             uuid.UUID
	ServerID           uuid.UUID
	RemoteName         string
	DisplayName        string
	Enabled            bool
	Zones              []string
	Lpr                bool
	LiveStream         string
	HqStream           string
	Status             string
	Fps                *float32
	MissingSince       *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	DeletedBy          *uuid.UUID
	DefaultLiveQuality string
	Description        string
	Location           string
	Tags               []string
}

type CameraGroup struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	DeletedBy   *uuid.UUID
}

type CameraGroupMember struct {
	GroupID  uuid.UUID
	CameraID uuid.UUID
	TenantID uuid.UUID
}

type CameraOutage struct {
	CameraID uuid.UUID
	TenantID uuid.UUID
	Since    time.Time
}

type ClipWatermarkJob struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	SiteID        uuid.UUID
	ServerID      uuid.UUID
	CameraID      uuid.UUID
	LprReadID     uuid.UUID
	RemoteEventID string
	RequestedBy   uuid.UUID
	WatermarkText string
	LogoKey       string
	Status        string
	Error         string
	OutputKey     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Event struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	SiteID        uuid.UUID
	ServerID      uuid.UUID
	CameraID      uuid.UUID
	RemoteID      string
	Severity      string
	Labels        []string
	SubLabels     []string
	Zones         []string
	Audio         []string
	Plates        []string
	DetectionIds  []string
	StartTime     time.Time
	EndTime       *time.Time
	Reviewed      bool
	ThumbKey      string
	ThumbAttempts int32
	FirstSeenAt   time.Time
	UpdatedAt     time.Time
	HasSnapshot   bool
	PreviewKey    string
	Lpr           bool
}

type EventSyncState struct {
	ServerID        uuid.UUID
	TenantID        uuid.UUID
	ReviewCursor    *time.Time
	ObjectCursor    *time.Time
	LastSuccessAt   *time.Time
	LastError       string
	BackfilledUntil *time.Time
	UpdatedAt       time.Time
}

type Export struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	SiteID      uuid.UUID
	ServerID    uuid.UUID
	CameraID    uuid.UUID
	RequestedBy uuid.UUID
	Name        string
	StartTime   time.Time
	EndTime     time.Time
	RemoteID    string
	Status      string
	Progress    float32
	Error       string
	RemotePath  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type FrigateServer struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SiteID         uuid.UUID
	Name           string
	BaseUrl        string
	Username       string
	PasswordSealed []byte
	TlsSkipVerify  bool
	FrigateVersion string
	Capabilities   json.RawMessage
	Status         string
	LastSeenAt     *time.Time
	LastCheckedAt  *time.Time
	LastError      string
	Stats          json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
	DeletedBy      *uuid.UUID
	AuthMode       string
}

type LprRead struct {
	ID              uuid.UUID
	TenantID        uuid.UUID
	SiteID          uuid.UUID
	ServerID        uuid.UUID
	CameraID        uuid.UUID
	RemoteEventID   string
	Plate           string
	PlateNormalized string
	Score           *float32
	Label           string
	SubLabel        string
	Zones           []string
	SeenAt          time.Time
	FirstSeenAt     time.Time
	UpdatedAt       time.Time
}

type Notification struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    *uuid.UUID
	RuleID    *uuid.UUID
	Title     string
	Body      string
	Link      *string
	Severity  string
	ReadAt    *time.Time
	CreatedAt time.Time
}

type NotificationChannel struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	Type          string
	Config        json.RawMessage
	SecretsSealed []byte
	Enabled       bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type NotificationDelivery struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ChannelID      *uuid.UUID
	ChannelName    string
	ChannelType    string
	RuleID         *uuid.UUID
	NotificationID *uuid.UUID
	Destination    string
	Payload        json.RawMessage
	Status         string
	Attempts       int32
	LastError      *string
	NextAttemptAt  time.Time
	CreatedAt      time.Time
	SentAt         *time.Time
}

type ObjectSnapshot struct {
	ServerID       uuid.UUID
	TenantID       uuid.UUID
	RemoteObjectID string
	SeenAt         time.Time
}

type PermissionGrant struct {
	ID          uuid.UUID
	TenantID    *uuid.UUID
	SubjectType string
	SubjectID   uuid.UUID
	Permission  string
	Effect      string
	ScopeType   string
	ScopeID     *uuid.UUID
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

type Rule struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	TriggerType string
	Conditions  json.RawMessage
	Actions     json.RawMessage
	Enabled     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RuleFiring struct {
	RuleID     uuid.UUID
	ResourceID uuid.UUID
	TenantID   uuid.UUID
	FiredAt    time.Time
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	Ip         *netip.Addr
	UserAgent  string
}

type Site struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Timezone  string
	Address   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	DeletedBy *uuid.UUID
}

type Tenant struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	DeletedBy *uuid.UUID
}

type TenantBranding struct {
	TenantID        uuid.UUID
	OwnerName       string
	LogoKey         string
	LogoContentType string
	UpdatedAt       time.Time
	UpdatedBy       *uuid.UUID
	Timezone        string
}

type User struct {
	ID                 uuid.UUID
	TenantID           *uuid.UUID
	Username           string
	Email              *string
	DisplayName        string
	Status             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	DeletedBy          *uuid.UUID
	PasswordHash       string
	PasswordChangedAt  *time.Time
	MustChangePassword bool
	MfaSecretSealed    []byte
	MfaEnabled         bool
	FailedLogins       int32
	LockedUntil        *time.Time
	LastLoginAt        *time.Time
}

type UserGroup struct {
	ID          uuid.UUID
	TenantID    *uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	DeletedBy   *uuid.UUID
}

type UserGroupMember struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

type View struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Shared    bool
	Layout    json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}
