// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*)::bigint
FROM notifications
WHERE tenant_id = $1
  AND (user_id IS NULL OR user_id = $2)
  AND read_at IS NULL
`

type CountUnreadNotificationsParams struct {
	TenantID uuid.UUID
	UserID   *uuid.UUID
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.TenantID, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (tenant_id, user_id, rule_id, title, body, link, severity)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, user_id, rule_id, title, body, link, severity, read_at, created_at
`

type CreateNotificationParams struct {
	TenantID uuid.UUID
	UserID   *uuid.UUID
	RuleID   *uuid.UUID
	Title    string
	Body     string
	Link     *string
	Severity string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.TenantID,
		arg.UserID,
		arg.RuleID,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.Severity,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RuleID,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Severity,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, tenant_id, user_id, rule_id, title, body, link, severity, read_at, created_at
FROM notifications
WHERE tenant_id = $1
  AND (user_id IS NULL OR user_id = $2)
  AND ($3::boolean IS NOT TRUE OR read_at IS NULL)
ORDER BY created_at DESC
LIMIT $4
`

type ListNotificationsParams struct {
	TenantID   uuid.UUID
	UserID     *uuid.UUID
	UnreadOnly *bool
	LimitCount int32
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.TenantID,
		arg.UserID,
		arg.UnreadOnly,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.RuleID,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.Severity,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read_at = now()
WHERE tenant_id = $1
  AND (user_id IS NULL OR user_id = $2)
  AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	TenantID uuid.UUID
	UserID   *uuid.UUID
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, arg.TenantID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read_at = now()
WHERE id = $1
  AND tenant_id = $2
  AND (user_id IS NULL OR user_id = $3)
RETURNING id, tenant_id, user_id, rule_id, title, body, link, severity, read_at, created_at
`

type MarkNotificationReadParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   *uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.TenantID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RuleID,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.Severity,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
