// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notify.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const claimDueNotificationDeliveries = `-- name: ClaimDueNotificationDeliveries :many
UPDATE notification_deliveries
SET attempts = attempts + 1,
    next_attempt_at = now() + make_interval(secs => $1::float8)
WHERE id IN (
  SELECT d.id FROM notification_deliveries d
  WHERE d.status = 'pending' AND d.next_attempt_at <= now()
  ORDER BY d.next_attempt_at
  LIMIT $2
  FOR UPDATE SKIP LOCKED)
RETURNING id, tenant_id, channel_id, channel_name, channel_type, rule_id, notification_id, destination, payload, status, attempts, last_error, next_attempt_at, created_at, sent_at
`

type ClaimDueNotificationDeliveriesParams struct {
	LeaseSeconds float64
	MaxRows      int32
}

// ClaimDueNotificationDeliveries leases due rows: attempts is bumped and next_attempt_at pushed
// out by the lease, so a worker that dies mid-send only delays the row instead of losing it.
func (q *Queries) ClaimDueNotificationDeliveries(ctx context.Context, arg ClaimDueNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, claimDueNotificationDeliveries, arg.LeaseSeconds, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelType,
			&i.RuleID,
			&i.NotificationID,
			&i.Destination,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countNotificationChannelsByIDs = `-- name: CountNotificationChannelsByIDs :one
SELECT count(*) FROM notification_channels
WHERE tenant_id = $1 AND id = ANY($2::uuid[])
`

type CountNotificationChannelsByIDsParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) CountNotificationChannelsByIDs(ctx context.Context, arg CountNotificationChannelsByIDsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationChannelsByIDs, arg.TenantID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (id, tenant_id, name, type, config, secrets_sealed, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, name, type, config, secrets_sealed, enabled, created_at, updated_at
`

type CreateNotificationChannelParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Name          string
	Type          string
	Config        json.RawMessage
	SecretsSealed []byte
	Enabled       bool
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.SecretsSealed,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretsSealed,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels
WHERE id = $1 AND tenant_id = $2
`

type DeleteNotificationChannelParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationChannel, arg.ID, arg.TenantID)
	return err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, tenant_id, name, type, config, secrets_sealed, enabled, created_at, updated_at FROM notification_channels
WHERE id = $1 AND tenant_id = $2
`

type GetNotificationChannelParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.TenantID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretsSealed,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNotificationDelivery = `-- name: InsertNotificationDelivery :exec
INSERT INTO notification_deliveries (tenant_id, channel_id, channel_name, channel_type, rule_id, notification_id, destination, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertNotificationDeliveryParams struct {
	TenantID       uuid.UUID
	ChannelID      *uuid.UUID
	ChannelName    string
	ChannelType    string
	RuleID         *uuid.UUID
	NotificationID *uuid.UUID
	Destination    string
	Payload        json.RawMessage
}

func (q *Queries) InsertNotificationDelivery(ctx context.Context, arg InsertNotificationDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertNotificationDelivery,
		arg.TenantID,
		arg.ChannelID,
		arg.ChannelName,
		arg.ChannelType,
		arg.RuleID,
		arg.NotificationID,
		arg.Destination,
		arg.Payload,
	)
	return err
}

const listEnabledNotificationChannelsByIDs = `-- name: ListEnabledNotificationChannelsByIDs :many
SELECT id, tenant_id, name, type, config, secrets_sealed, enabled, created_at, updated_at FROM notification_channels
WHERE tenant_id = $1 AND enabled = true AND id = ANY($2::uuid[])
`

type ListEnabledNotificationChannelsByIDsParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) ListEnabledNotificationChannelsByIDs(ctx context.Context, arg ListEnabledNotificationChannelsByIDsParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledNotificationChannelsByIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.SecretsSealed,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, tenant_id, name, type, config, secrets_sealed, enabled, created_at, updated_at FROM notification_channels
WHERE tenant_id = $1
ORDER BY name ASC, created_at DESC
`

func (q *Queries) ListNotificationChannels(ctx context.Context, tenantID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.SecretsSealed,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
SELECT id, tenant_id, channel_id, channel_name, channel_type, rule_id, notification_id, destination, payload, status, attempts, last_error, next_attempt_at, created_at, sent_at FROM notification_deliveries
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR channel_id = $2)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListNotificationDeliveriesParams struct {
	TenantID  uuid.UUID
	ChannelID *uuid.UUID
	MaxRows   int32
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.Query(ctx, listNotificationDeliveries, arg.TenantID, arg.ChannelID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChannelID,
			&i.ChannelName,
			&i.ChannelType,
			&i.RuleID,
			&i.NotificationID,
			&i.Destination,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationDeliveryFailed = `-- name: MarkNotificationDeliveryFailed :exec
UPDATE notification_deliveries
SET status = 'failed', last_error = $1
WHERE id = $2
`

type MarkNotificationDeliveryFailedParams struct {
	LastError *string
	ID        uuid.UUID
}

func (q *Queries) MarkNotificationDeliveryFailed(ctx context.Context, arg MarkNotificationDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationDeliveryFailed, arg.LastError, arg.ID)
	return err
}

const markNotificationDeliveryRetry = `-- name: MarkNotificationDeliveryRetry :exec
UPDATE notification_deliveries
SET last_error = $1,
    next_attempt_at = now() + make_interval(secs => $2::float8)
WHERE id = $3
`

type MarkNotificationDeliveryRetryParams struct {
	LastError    *string
	DelaySeconds float64
	ID           uuid.UUID
}

func (q *Queries) MarkNotificationDeliveryRetry(ctx context.Context, arg MarkNotificationDeliveryRetryParams) error {
	_, err := q.db.Exec(ctx, markNotificationDeliveryRetry, arg.LastError, arg.DelaySeconds, arg.ID)
	return err
}

const markNotificationDeliverySent = `-- name: MarkNotificationDeliverySent :exec
UPDATE notification_deliveries
SET status = 'sent', sent_at = now(), last_error = NULL
WHERE id = $1
`

func (q *Queries) MarkNotificationDeliverySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationDeliverySent, id)
	return err
}

const stripChannelFromRules = `-- name: StripChannelFromRules :exec
UPDATE rules
SET actions = jsonb_set(
      actions, '{channel_ids}',
      coalesce((SELECT jsonb_agg(v) FROM jsonb_array_elements(actions->'channel_ids') AS v WHERE (v #>> '{}') <> $1::text), '[]'::jsonb))
WHERE tenant_id = $2
  AND jsonb_typeof(actions->'channel_ids') = 'array'
  AND actions->'channel_ids' @> to_jsonb($1::text)
`

type StripChannelFromRulesParams struct {
	ChannelID string
	TenantID  uuid.UUID
}

func (q *Queries) StripChannelFromRules(ctx context.Context, arg StripChannelFromRulesParams) error {
	_, err := q.db.Exec(ctx, stripChannelFromRules, arg.ChannelID, arg.TenantID)
	return err
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET
  name = coalesce($1, name),
  config = coalesce($2, config),
  secrets_sealed = coalesce($3, secrets_sealed),
  enabled = coalesce($4, enabled),
  updated_at = now()
WHERE id = $5 AND tenant_id = $6
RETURNING id, tenant_id, name, type, config, secrets_sealed, enabled, created_at, updated_at
`

type UpdateNotificationChannelParams struct {
	Name          *string
	Config        []byte
	SecretsSealed []byte
	Enabled       *bool
	ID            uuid.UUID
	TenantID      uuid.UUID
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.Name,
		arg.Config,
		arg.SecretsSealed,
		arg.Enabled,
		arg.ID,
		arg.TenantID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretsSealed,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
