// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (tenant_id, name, trigger_type, conditions, actions, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, trigger_type, conditions, actions, enabled, created_at, updated_at
`

type CreateRuleParams struct {
	TenantID    uuid.UUID
	Name        string
	TriggerType string
	Conditions  json.RawMessage
	Actions     json.RawMessage
	Enabled     bool
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.TenantID,
		arg.Name,
		arg.TriggerType,
		arg.Conditions,
		arg.Actions,
		arg.Enabled,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TriggerType,
		&i.Conditions,
		&i.Actions,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules
WHERE id = $1 AND tenant_id = $2
`

type DeleteRuleParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) error {
	_, err := q.db.Exec(ctx, deleteRule, arg.ID, arg.TenantID)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, tenant_id, name, trigger_type, conditions, actions, enabled, created_at, updated_at
FROM rules
WHERE id = $1 AND tenant_id = $2
`

type GetRuleParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, getRule, arg.ID, arg.TenantID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TriggerType,
		&i.Conditions,
		&i.Actions,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRulesByTrigger = `-- name: ListActiveRulesByTrigger :many
SELECT id, tenant_id, name, trigger_type, conditions, actions, enabled, created_at, updated_at
FROM rules
WHERE tenant_id = $1 AND trigger_type = $2 AND enabled = true
ORDER BY created_at ASC
`

type ListActiveRulesByTriggerParams struct {
	TenantID    uuid.UUID
	TriggerType string
}

func (q *Queries) ListActiveRulesByTrigger(ctx context.Context, arg ListActiveRulesByTriggerParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listActiveRulesByTrigger, arg.TenantID, arg.TriggerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TriggerType,
			&i.Conditions,
			&i.Actions,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, tenant_id, name, trigger_type, conditions, actions, enabled, created_at, updated_at
FROM rules
WHERE tenant_id = $1
ORDER BY name ASC, created_at DESC
`

func (q *Queries) ListRules(ctx context.Context, tenantID uuid.UUID) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.TriggerType,
			&i.Conditions,
			&i.Actions,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET
  name = coalesce($1, name),
  trigger_type = coalesce($2, trigger_type),
  conditions = coalesce($3, conditions),
  actions = coalesce($4, actions),
  enabled = coalesce($5, enabled),
  updated_at = now()
WHERE id = $6 AND tenant_id = $7
RETURNING id, tenant_id, name, trigger_type, conditions, actions, enabled, created_at, updated_at
`

type UpdateRuleParams struct {
	Name        *string
	TriggerType *string
	Conditions  []byte
	Actions     []byte
	Enabled     *bool
	ID          uuid.UUID
	TenantID    uuid.UUID
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.Name,
		arg.TriggerType,
		arg.Conditions,
		arg.Actions,
		arg.Enabled,
		arg.ID,
		arg.TenantID,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.TriggerType,
		&i.Conditions,
		&i.Actions,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
