// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const searchCameras = `-- name: SearchCameras :many
SELECT c.id, c.display_name, c.site_id, s.name AS site_name, c.location, c.status
FROM cameras c
JOIN sites s ON s.id = c.site_id
WHERE c.deleted_at IS NULL
  AND c.id = ANY($1::uuid[])
  AND (
    c.display_name ILIKE '%' || $2::text || '%'
    OR c.location ILIKE '%' || $2::text || '%'
    OR $2::text = ANY(c.tags)
  )
ORDER BY c.display_name
LIMIT 5
`

type SearchCamerasParams struct {
	CameraIds []uuid.UUID
	Query     string
}

type SearchCamerasRow struct {
	ID          uuid.UUID
	DisplayName string
	SiteID      uuid.UUID
	SiteName    string
	Location    string
	Status      string
}

func (q *Queries) SearchCameras(ctx context.Context, arg SearchCamerasParams) ([]SearchCamerasRow, error) {
	rows, err := q.db.Query(ctx, searchCameras, arg.CameraIds, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCamerasRow{}
	for rows.Next() {
		var i SearchCamerasRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.SiteID,
			&i.SiteName,
			&i.Location,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEvents = `-- name: SearchEvents :many
SELECT e.id, e.camera_id, c.display_name AS camera_name, s.name AS site_name,
       e.severity, e.labels, e.start_time, (e.thumb_key <> '') AS has_thumbnail
FROM events e
JOIN cameras c ON c.id = e.camera_id
JOIN sites s ON s.id = e.site_id
WHERE e.camera_id = ANY($1::uuid[])
  AND (
    e.labels && ARRAY[$2::text]
    OR EXISTS (SELECT 1 FROM unnest(e.labels) l WHERE l ILIKE '%' || $2::text || '%')
    OR e.remote_id ILIKE '%' || $2::text || '%'
  )
ORDER BY e.start_time DESC
LIMIT 5
`

type SearchEventsParams struct {
	CameraIds []uuid.UUID
	Query     string
}

type SearchEventsRow struct {
	ID           uuid.UUID
	CameraID     uuid.UUID
	CameraName   string
	SiteName     string
	Severity     string
	Labels       []string
	StartTime    time.Time
	HasThumbnail bool
}

func (q *Queries) SearchEvents(ctx context.Context, arg SearchEventsParams) ([]SearchEventsRow, error) {
	rows, err := q.db.Query(ctx, searchEvents, arg.CameraIds, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEventsRow{}
	for rows.Next() {
		var i SearchEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.CameraName,
			&i.SiteName,
			&i.Severity,
			&i.Labels,
			&i.StartTime,
			&i.HasThumbnail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPlates = `-- name: SearchPlates :many
SELECT l.plate, l.camera_id, c.display_name AS camera_name, s.name AS site_name,
       l.seen_at,
       e.id AS event_id
FROM lpr_reads l
JOIN cameras c ON c.id = l.camera_id
JOIN sites s ON s.id = l.site_id
LEFT JOIN events e ON e.server_id = l.server_id AND l.remote_event_id = ANY(e.detection_ids)
WHERE l.camera_id = ANY($1::uuid[])
  AND l.plate_normalized ILIKE '%' || $2::text || '%'
ORDER BY l.seen_at DESC
LIMIT 5
`

type SearchPlatesParams struct {
	CameraIds []uuid.UUID
	Query     string
}

type SearchPlatesRow struct {
	Plate      string
	CameraID   uuid.UUID
	CameraName string
	SiteName   string
	SeenAt     time.Time
	EventID    *uuid.UUID
}

func (q *Queries) SearchPlates(ctx context.Context, arg SearchPlatesParams) ([]SearchPlatesRow, error) {
	rows, err := q.db.Query(ctx, searchPlates, arg.CameraIds, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlatesRow{}
	for rows.Next() {
		var i SearchPlatesRow
		if err := rows.Scan(
			&i.Plate,
			&i.CameraID,
			&i.CameraName,
			&i.SiteName,
			&i.SeenAt,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServers = `-- name: SearchServers :many
SELECT fs.id, fs.name, fs.site_id, s.name AS site_name, fs.status
FROM frigate_servers fs
JOIN sites s ON s.id = fs.site_id
WHERE fs.deleted_at IS NULL
  AND fs.id = ANY($1::uuid[])
  AND fs.name ILIKE '%' || $2::text || '%'
ORDER BY fs.name
LIMIT 5
`

type SearchServersParams struct {
	ServerIds []uuid.UUID
	Query     string
}

type SearchServersRow struct {
	ID       uuid.UUID
	Name     string
	SiteID   uuid.UUID
	SiteName string
	Status   string
}

func (q *Queries) SearchServers(ctx context.Context, arg SearchServersParams) ([]SearchServersRow, error) {
	rows, err := q.db.Query(ctx, searchServers, arg.ServerIds, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchServersRow{}
	for rows.Next() {
		var i SearchServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SiteID,
			&i.SiteName,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSites = `-- name: SearchSites :many
SELECT s.id, s.name,
       (SELECT count(*) FROM cameras c WHERE c.site_id = s.id AND c.deleted_at IS NULL)::int AS camera_count
FROM sites s
WHERE s.deleted_at IS NULL
  AND s.id = ANY($1::uuid[])
  AND s.name ILIKE '%' || $2::text || '%'
ORDER BY s.name
LIMIT 5
`

type SearchSitesParams struct {
	SiteIds []uuid.UUID
	Query   string
}

type SearchSitesRow struct {
	ID          uuid.UUID
	Name        string
	CameraCount int32
}

func (q *Queries) SearchSites(ctx context.Context, arg SearchSitesParams) ([]SearchSitesRow, error) {
	rows, err := q.db.Query(ctx, searchSites, arg.SiteIds, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSitesRow{}
	for rows.Next() {
		var i SearchSitesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CameraCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
