// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_agent_tls.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteServerAgentTLS = `-- name: DeleteServerAgentTLS :execrows
DELETE FROM server_agent_tls WHERE server_id = $1
`

func (q *Queries) DeleteServerAgentTLS(ctx context.Context, serverID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServerAgentTLS, serverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServerAgentTLS = `-- name: GetServerAgentTLS :one
SELECT server_id, tenant_id, secure_port, trust_mode, ca_pem
FROM server_agent_tls
WHERE server_id = $1
FOR UPDATE
`

func (q *Queries) GetServerAgentTLS(ctx context.Context, serverID uuid.UUID) (ServerAgentTl, error) {
	row := q.db.QueryRow(ctx, getServerAgentTLS, serverID)
	var i ServerAgentTl
	err := row.Scan(
		&i.ServerID,
		&i.TenantID,
		&i.SecurePort,
		&i.TrustMode,
		&i.CaPem,
	)
	return i, err
}

const upsertServerAgentTLS = `-- name: UpsertServerAgentTLS :exec
INSERT INTO server_agent_tls (server_id, tenant_id, secure_port, trust_mode, ca_pem)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (server_id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    secure_port = EXCLUDED.secure_port,
    trust_mode = EXCLUDED.trust_mode,
    ca_pem = EXCLUDED.ca_pem
`

type UpsertServerAgentTLSParams struct {
	ServerID   uuid.UUID
	TenantID   uuid.UUID
	SecurePort int32
	TrustMode  string
	CaPem      *string
}

func (q *Queries) UpsertServerAgentTLS(ctx context.Context, arg UpsertServerAgentTLSParams) error {
	_, err := q.db.Exec(ctx, upsertServerAgentTLS,
		arg.ServerID,
		arg.TenantID,
		arg.SecurePort,
		arg.TrustMode,
		arg.CaPem,
	)
	return err
}
