// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_agent_ssh_host_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimServerAgentSSHHostKey = `-- name: ClaimServerAgentSSHHostKey :execrows
INSERT INTO server_agent_ssh_host_keys (server_id, tenant_id, host, ssh_port, fingerprint)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (server_id, host, ssh_port) DO NOTHING
`

type ClaimServerAgentSSHHostKeyParams struct {
	ServerID    uuid.UUID
	TenantID    uuid.UUID
	Host        string
	SshPort     int32
	Fingerprint string
}

func (q *Queries) ClaimServerAgentSSHHostKey(ctx context.Context, arg ClaimServerAgentSSHHostKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimServerAgentSSHHostKey,
		arg.ServerID,
		arg.TenantID,
		arg.Host,
		arg.SshPort,
		arg.Fingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServerAgentSSHHostKey = `-- name: GetServerAgentSSHHostKey :one
SELECT server_id, tenant_id, host, ssh_port, fingerprint
FROM server_agent_ssh_host_keys
WHERE server_id = $1 AND host = $2 AND ssh_port = $3
FOR UPDATE
`

type GetServerAgentSSHHostKeyParams struct {
	ServerID uuid.UUID
	Host     string
	SshPort  int32
}

type GetServerAgentSSHHostKeyRow struct {
	ServerID    uuid.UUID
	TenantID    uuid.UUID
	Host        string
	SshPort     int32
	Fingerprint string
}

func (q *Queries) GetServerAgentSSHHostKey(ctx context.Context, arg GetServerAgentSSHHostKeyParams) (GetServerAgentSSHHostKeyRow, error) {
	row := q.db.QueryRow(ctx, getServerAgentSSHHostKey, arg.ServerID, arg.Host, arg.SshPort)
	var i GetServerAgentSSHHostKeyRow
	err := row.Scan(
		&i.ServerID,
		&i.TenantID,
		&i.Host,
		&i.SshPort,
		&i.Fingerprint,
	)
	return i, err
}
