// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: server_agents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getServerAgent = `-- name: GetServerAgent :one
SELECT server_id, tenant_id, host, port, variant, token_sealed, version, updated_at
FROM server_agents
WHERE server_id = $1
`

func (q *Queries) GetServerAgent(ctx context.Context, serverID uuid.UUID) (ServerAgent, error) {
	row := q.db.QueryRow(ctx, getServerAgent, serverID)
	var i ServerAgent
	err := row.Scan(
		&i.ServerID,
		&i.TenantID,
		&i.Host,
		&i.Port,
		&i.Variant,
		&i.TokenSealed,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerAgentForUpdate = `-- name: GetServerAgentForUpdate :one
SELECT server_id, tenant_id, host, port, variant, token_sealed, version, updated_at
FROM server_agents
WHERE server_id = $1
FOR UPDATE
`

func (q *Queries) GetServerAgentForUpdate(ctx context.Context, serverID uuid.UUID) (ServerAgent, error) {
	row := q.db.QueryRow(ctx, getServerAgentForUpdate, serverID)
	var i ServerAgent
	err := row.Scan(
		&i.ServerID,
		&i.TenantID,
		&i.Host,
		&i.Port,
		&i.Variant,
		&i.TokenSealed,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const registerServerAgentIfAbsent = `-- name: RegisterServerAgentIfAbsent :execrows
INSERT INTO server_agents (server_id, tenant_id, host, port, variant, token_sealed, version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (server_id) DO NOTHING
`

type RegisterServerAgentIfAbsentParams struct {
	ServerID    uuid.UUID
	TenantID    uuid.UUID
	Host        string
	Port        int32
	Variant     string
	TokenSealed []byte
	Version     string
}

// Local Compose registration must not replace a previously provisioned agent token.
func (q *Queries) RegisterServerAgentIfAbsent(ctx context.Context, arg RegisterServerAgentIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, registerServerAgentIfAbsent,
		arg.ServerID,
		arg.TenantID,
		arg.Host,
		arg.Port,
		arg.Variant,
		arg.TokenSealed,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateServerAgentVersion = `-- name: UpdateServerAgentVersion :exec
UPDATE server_agents SET version = $1, updated_at = now()
WHERE server_id = $2
`

type UpdateServerAgentVersionParams struct {
	Version  string
	ServerID uuid.UUID
}

func (q *Queries) UpdateServerAgentVersion(ctx context.Context, arg UpdateServerAgentVersionParams) error {
	_, err := q.db.Exec(ctx, updateServerAgentVersion, arg.Version, arg.ServerID)
	return err
}

const upsertServerAgent = `-- name: UpsertServerAgent :exec
INSERT INTO server_agents (server_id, tenant_id, host, port, variant, token_sealed, version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (server_id) DO UPDATE SET
    tenant_id = EXCLUDED.tenant_id,
    host = EXCLUDED.host,
    port = EXCLUDED.port,
    variant = EXCLUDED.variant,
    token_sealed = EXCLUDED.token_sealed,
    version = EXCLUDED.version,
    updated_at = now()
`

type UpsertServerAgentParams struct {
	ServerID    uuid.UUID
	TenantID    uuid.UUID
	Host        string
	Port        int32
	Variant     string
	TokenSealed []byte
	Version     string
}

func (q *Queries) UpsertServerAgent(ctx context.Context, arg UpsertServerAgentParams) error {
	_, err := q.db.Exec(ctx, upsertServerAgent,
		arg.ServerID,
		arg.TenantID,
		arg.Host,
		arg.Port,
		arg.Variant,
		arg.TokenSealed,
		arg.Version,
	)
	return err
}
