/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 while the process is running. Does not check dependencies.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks every backing service. Returns 503 when any required dependency is down.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build and runtime information */
        get: operations["getSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user and their permissions */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Permission catalog
         * @description Every permission the VMS knows and the narrowest scope it can be granted at.
         */
        get: operations["listPermissionCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List grants
         * @description Grants whose scope the caller can manage (permissions.manage).
         */
        get: operations["listGrants"];
        put?: never;
        /**
         * Grant or deny a permission on a scope
         * @description Requires permissions.manage on the scope. Callers cannot grant a permission they do not
         *     hold themselves on that scope.
         */
        post: operations["createGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/grants/{grantId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grantId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a grant */
        delete: operations["deleteGrant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenants visible to the caller */
        get: operations["listTenants"];
        put?: never;
        /** Create a tenant (platform administrators) */
        post: operations["createTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sites the caller can view */
        get: operations["listSites"];
        put?: never;
        /** Create a site */
        post: operations["createSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sites/{siteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                siteId: string;
            };
            cookie?: never;
        };
        /** Get a site */
        get: operations["getSite"];
        put?: never;
        post?: never;
        /** Soft-delete an empty site */
        delete: operations["deleteSite"];
        options?: never;
        head?: never;
        /** Update a site */
        patch: operations["updateSite"];
        trace?: never;
    };
    "/api/v1/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Frigate servers the caller can view */
        get: operations["listServers"];
        put?: never;
        /**
         * Register a Frigate server
         * @description Connects with the given credentials, detects version and capabilities and, when
         *     import_cameras is true, imports every camera. Credentials are stored encrypted.
         */
        post: operations["createServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a Frigate connection without saving it
         * @description Wizard step 3. Requires servers.manage on the target site.
         */
        post: operations["probeServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/servers/{serverId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        /** Get a Frigate server */
        get: operations["getServer"];
        put?: never;
        post?: never;
        /**
         * Remove a server and its cameras from the VMS (soft delete)
         * @description Frigate itself is not touched.
         */
        delete: operations["deleteServer"];
        options?: never;
        head?: never;
        /** Rename, move or change the credentials of a server */
        patch: operations["updateServer"];
        trace?: never;
    };
    "/api/v1/servers/{serverId}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rediscover version, capabilities and cameras */
        post: operations["syncServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cameras the caller can view
         * @description Only cameras covered by cameras.view are returned; the total never counts others.
         */
        get: operations["listCameras"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{cameraId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        /** Get a camera */
        get: operations["getCamera"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename or enable/disable a camera in the VMS */
        patch: operations["updateCamera"];
        trace?: never;
    };
    "/api/v1/camera-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List camera groups */
        get: operations["listCameraGroups"];
        put?: never;
        /**
         * Create a camera group
         * @description Requires cameras.manage on the tenant and on every member camera.
         */
        post: operations["createCameraGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/camera-groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        /** Get a camera group */
        get: operations["getCameraGroup"];
        /** Replace name, description and members of a camera group */
        put: operations["replaceCameraGroup"];
        post?: never;
        /** Delete a camera group */
        delete: operations["deleteCameraGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the federated event index
         * @description Review items from every Frigate the caller can see, newest first, with keyset
         *     pagination. Filtering by label, zone, sub_label, time or plate needs events.search;
         *     plates are only returned and searchable on cameras with lpr.view / lpr.search.
         */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/sync-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event ingestion state per Frigate server */
        get: operations["listEventSyncStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        /** Get an event */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mark an event reviewed or not (events.review) */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/api/v1/events/{eventId}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        /**
         * Event thumbnail
         * @description The copy kept by the VMS, or the one in the origin Frigate while it has not been copied yet.
         */
        get: operations["getEventThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lpr/reads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search plate reads across every authorized Frigate
         * @description Needs lpr.view to list and lpr.search to filter by plate.
         */
        get: operations["listPlateReads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with username and password (and TOTP when enabled)
         * @description On success sets the HttpOnly session cookie. When the account has MFA and no
         *     totp_code was sent, answers mfa_required without opening a session. After
         *     repeated failures the account locks for a while (429).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current browser session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password
         * @description Other sessions of the user are closed.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start TOTP enrolment
         * @description Returns a new secret. MFA is only enforced after enableMfa confirms a code.
         */
        post: operations["setupMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/mfa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a TOTP code and turn MFA on */
        post: operations["enableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn MFA off (needs the password) */
        post: operations["disableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (users.view) */
        get: operations["listUsers"];
        put?: never;
        /** Create a user (users.manage; groups.manage to add groups) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        /** Get a user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /** Remove a user (soft delete, sessions closed) */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /** Update, disable, reset the password or MFA of a user (users.manage) */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user groups (groups.view) */
        get: operations["listUserGroups"];
        put?: never;
        /** Create a user group (groups.manage) */
        post: operations["createUserGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        /** Get a user group */
        get: operations["getUserGroup"];
        /** Rename a group and replace its members */
        put: operations["replaceUserGroup"];
        post?: never;
        /** Delete a user group (its grants stop applying) */
        delete: operations["deleteUserGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the audit trail (audit.view) */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your views and the shared views of your tenant
         * @description Tiles with cameras you cannot watch come back empty.
         */
        get: operations["listViews"];
        put?: never;
        /** Save a view (views.create_private, or views.create_shared when shared) */
        post: operations["createView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/views/{viewId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        /** Get a view */
        get: operations["getView"];
        /** Change a view (owner, or views.manage_shared for shared views) */
        put: operations["replaceView"];
        post?: never;
        /** Delete a view */
        delete: operations["deleteView"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{cameraId}/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        /**
         * Recorded spans of a camera, read from its Frigate (recordings.seek)
         * @description Play a span through the media gateway:
         *     /media/v1/cameras/{cameraId}/vod/{start_unix}/{end_unix}/master.m3u8 (HLS).
         */
        get: operations["listCameraRecordings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your exports and those of cameras where you hold exports.download */
        get: operations["listExports"];
        put?: never;
        /**
         * Export a clip from the camera's Frigate (exports.create)
         * @description Frigate encodes the file; the VMS follows it until ready. Download it from
         *     /media/v1/exports/{exportId}/download (exports.download).
         */
        post: operations["createExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/{exportId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: string;
            };
            cookie?: never;
        };
        /** Get an export */
        get: operations["getExport"];
        put?: never;
        post?: never;
        /** Remove an export from the VMS list (the file in Frigate is untouched) */
        delete: operations["deleteExport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            mfa_enabled: boolean;
            must_change_password: boolean;
            /**
             * @description How this request was authenticated.
             * @enum {string}
             */
            auth_method: "session" | "token";
            /**
             * Format: uuid
             * @description Null for platform users.
             */
            tenant_id: string | null;
            grants: components["schemas"]["Grant"][];
        };
        /** @enum {string} */
        SubjectType: "user" | "group";
        /** @enum {string} */
        ScopeType: "platform" | "tenant" | "site" | "server" | "camera_group" | "camera";
        /** @enum {string} */
        Effect: "allow" | "deny";
        PermissionDefinition: {
            /** @example live.view */
            permission: string;
            description: string;
            narrowest_scope: components["schemas"]["ScopeType"];
        };
        GrantInput: {
            subject_type: components["schemas"]["SubjectType"];
            /** Format: uuid */
            subject_id: string;
            /** @example live.view */
            permission: string;
            effect: components["schemas"]["Effect"];
            scope_type: components["schemas"]["ScopeType"];
            /**
             * Format: uuid
             * @description Required unless scope_type is platform.
             */
            scope_id?: string;
        };
        Grant: components["schemas"]["GrantInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        TenantInput: {
            /** @example municipalidad-helvecia */
            slug: string;
            name: string;
        };
        Tenant: components["schemas"]["TenantInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            created_at: string;
        };
        SiteCreate: {
            /** Format: uuid */
            tenant_id: string;
            name: string;
            /** @example America/Argentina/Cordoba */
            timezone?: string;
            address?: string;
        };
        SiteUpdate: {
            name?: string;
            timezone?: string;
            address?: string;
        };
        Site: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            timezone: string;
            address: string;
            server_count: number;
            /** @description Cameras in this site the caller can view. */
            camera_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        HealthStatus: "unknown" | "online" | "degraded" | "offline";
        /**
         * @description credentials logs in with a Frigate user on the authenticated port (8971).
         *     none is for a Frigate without login (internal port 5000 or auth disabled); use it only
         *     on trusted networks.
         * @enum {string}
         */
        AuthMode: "credentials" | "none";
        ServerProbe: {
            /** Format: uuid */
            site_id: string;
            /**
             * @description Frigate URL. Port 5000 is only accepted with auth_mode none.
             * @example https://10.20.0.11:8971
             */
            base_url: string;
            auth_mode?: components["schemas"]["AuthMode"];
            /** @description Required with auth_mode credentials. */
            username?: string;
            /**
             * Format: password
             * @description Required with auth_mode credentials. Stored encrypted.
             */
            password?: string;
            /**
             * @description Accept Frigate's self-signed certificate.
             * @default false
             */
            tls_skip_verify: boolean;
        };
        ServerCreate: components["schemas"]["ServerProbe"] & {
            /** @example Frigate-H01 */
            name: string;
            /** @default true */
            import_cameras: boolean;
        };
        ServerUpdate: {
            name?: string;
            /** Format: uuid */
            site_id?: string;
            base_url?: string;
            auth_mode?: components["schemas"]["AuthMode"];
            username?: string;
            /** Format: password */
            password?: string;
            tls_skip_verify?: boolean;
        };
        Capabilities: {
            review: boolean;
            preview: boolean;
            exports: boolean;
            lpr: boolean;
            face_recognition: boolean;
            semantic_search: boolean;
            audio: boolean;
            ptz: boolean;
        };
        DiscoveredCamera: {
            remote_name: string;
            enabled: boolean;
            zones: string[];
            lpr: boolean;
        };
        ProbeResult: {
            /** @example 0.17.2 */
            frigate_version: string;
            /**
             * @description Adapter chosen for this version.
             * @example v017
             */
            adapter: string;
            capabilities: components["schemas"]["Capabilities"];
            cameras: components["schemas"]["DiscoveredCamera"][];
        };
        ServerStorage: {
            total_mb: number;
            used_mb: number;
            free_mb: number;
        };
        Server: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            site_id: string;
            name: string;
            base_url: string;
            auth_mode: components["schemas"]["AuthMode"];
            username: string;
            tls_skip_verify: boolean;
            frigate_version: string;
            capabilities: components["schemas"]["Capabilities"];
            status: components["schemas"]["HealthStatus"];
            /** Format: date-time */
            last_seen_at?: string | null;
            /** Format: date-time */
            last_checked_at?: string | null;
            last_error: string;
            uptime_seconds?: number | null;
            storage?: components["schemas"]["ServerStorage"];
            camera_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SyncResult: {
            server: components["schemas"]["Server"];
            added: number;
            updated: number;
            /** @description Cameras no longer present in Frigate. They are kept and flagged, not deleted. */
            missing: number;
        };
        Camera: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            site_id: string;
            /** Format: uuid */
            server_id: string;
            /** @description Camera name inside its Frigate server. */
            remote_name: string;
            display_name: string;
            enabled: boolean;
            zones: string[];
            lpr: boolean;
            status: components["schemas"]["HealthStatus"];
            fps?: number | null;
            /** Format: date-time */
            missing_since?: string | null;
            group_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CameraUpdate: {
            display_name?: string;
            enabled?: boolean;
        };
        CameraGroupInput: {
            /** Format: uuid */
            tenant_id: string;
            name: string;
            description?: string;
            camera_ids: string[];
        };
        CameraGroup: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            description: string;
            /** @description Members the caller can view. */
            camera_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        LivenessStatus: {
            /** @enum {string} */
            status: "ok";
        };
        ReadinessStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            checks: components["schemas"]["DependencyCheck"][];
        };
        DependencyCheck: {
            /** @example postgres */
            name: string;
            /** @enum {string} */
            status: "ok" | "error";
            /** Format: int64 */
            latency_ms: number;
            error?: string;
        };
        SystemInfo: {
            /** @example openvms-api */
            name: string;
            /** @example v0.1.0 */
            version: string;
            commit: string;
            build_time: string;
            go_version: string;
            /**
             * Format: int64
             * @description Latest applied database migration.
             */
            schema_version: number;
        };
        Error: {
            code: string;
            message: string;
            request_id?: string;
        };
        /** @enum {string} */
        Severity: "alert" | "detection";
        Event: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            site_id: string;
            site_name: string;
            /** Format: uuid */
            server_id: string;
            server_name: string;
            /** Format: uuid */
            camera_id: string;
            camera_name: string;
            /** @description Review id inside the origin Frigate. */
            remote_id: string;
            severity: components["schemas"]["Severity"];
            labels: string[];
            sub_labels: string[];
            zones: string[];
            /** @description Normalized plates read during the event. Empty without lpr.view. */
            plates: string[];
            /** Format: date-time */
            start_time: string;
            /**
             * Format: date-time
             * @description Null while the event is in progress.
             */
            end_time?: string | null;
            reviewed: boolean;
            /** @description The VMS keeps its own copy of the thumbnail. */
            has_thumbnail: boolean;
        };
        EventPage: {
            items: components["schemas"]["Event"][];
            /** @description Pass as cursor to get the next page. Absent on the last page. */
            next_cursor?: string;
        };
        EventSyncStatus: {
            /** Format: uuid */
            server_id: string;
            /** Format: date-time */
            review_cursor?: string | null;
            /** Format: date-time */
            object_cursor?: string | null;
            /** Format: date-time */
            last_success_at?: string | null;
            last_error: string;
            /** Format: int64 */
            event_count: number;
        };
        PlateRead: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            site_id: string;
            site_name: string;
            /** Format: uuid */
            server_id: string;
            server_name: string;
            /** Format: uuid */
            camera_id: string;
            camera_name: string;
            /** @description As read by Frigate. */
            plate: string;
            /** @example AB123CD */
            plate_normalized: string;
            score?: number | null;
            /** @example car */
            label: string;
            zones: string[];
            /** Format: date-time */
            seen_at: string;
            /**
             * Format: uuid
             * @description Indexed event that contains this read, when known.
             */
            event_id?: string | null;
        };
        PlateReadPage: {
            items: components["schemas"]["PlateRead"][];
            next_cursor?: string;
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
            totp_code?: string;
        };
        LoginResponse: {
            /** @description True when the password was right and a TOTP code must be sent too. */
            mfa_required: boolean;
            /** Format: date-time */
            expires_at?: string;
            user?: components["schemas"]["Me"];
        };
        /** @enum {string} */
        UserStatus: "active" | "disabled" | "locked" | "pending";
        User: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Null for platform users.
             */
            tenant_id: string | null;
            username: string;
            display_name: string;
            email?: string | null;
            status: components["schemas"]["UserStatus"];
            mfa_enabled: boolean;
            /** @description False for users that only use API tokens. */
            has_password: boolean;
            must_change_password: boolean;
            /** Format: date-time */
            locked_until?: string | null;
            /** Format: date-time */
            last_login_at?: string | null;
            group_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserCreate: {
            /**
             * Format: uuid
             * @description Defaults to the caller's tenant. Omit (platform administrators) for a platform user.
             */
            tenant_id?: string;
            username: string;
            display_name?: string;
            email?: string;
            /**
             * Format: password
             * @description Omit for a user that only uses API tokens.
             */
            password?: string;
            /** @default false */
            must_change_password: boolean;
            group_ids?: string[];
        };
        UserUpdate: {
            display_name?: string;
            email?: string;
            /** @enum {string} */
            status?: "active" | "disabled" | "locked";
            /**
             * Format: password
             * @description Resets the password and closes the user's sessions.
             */
            password?: string;
            must_change_password?: boolean;
            group_ids?: string[];
            /** @description Removes the second factor (lost phone). */
            disable_mfa?: boolean;
        };
        UserGroupInput: {
            /**
             * Format: uuid
             * @description Defaults to the caller's tenant.
             */
            tenant_id?: string;
            name: string;
            description?: string;
            member_ids?: string[];
        };
        UserGroup: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string | null;
            name: string;
            description: string;
            member_ids: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AuditEntry: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            occurred_at: string;
            /** Format: uuid */
            tenant_id?: string | null;
            /** Format: uuid */
            actor_id?: string | null;
            actor_name: string;
            /** @example LOGIN_SUCCESS */
            action: string;
            target_type: string;
            /** Format: uuid */
            target_id?: string | null;
            request_id: string;
            ip?: string | null;
            details: {
                [key: string]: unknown;
            };
        };
        /** @description A tile. Without camera_id it is empty. */
        ViewCell: {
            /** Format: uuid */
            camera_id?: string;
            /**
             * @default sub
             * @enum {string}
             */
            quality: "sub" | "main";
        };
        ViewLayout: {
            columns: number;
            /** @description Tiles in reading order. */
            cells: components["schemas"]["ViewCell"][];
        };
        ViewInput: {
            /**
             * Format: uuid
             * @description Required for platform users.
             */
            tenant_id?: string;
            name: string;
            /** @default false */
            shared: boolean;
            layout: components["schemas"]["ViewLayout"];
        };
        View: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            owner_id: string;
            name: string;
            shared: boolean;
            layout: components["schemas"]["ViewLayout"];
            /** @description The caller may change or delete it. */
            editable: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RecordingSpan: {
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            motion: number;
            objects: number;
        };
        ExportInput: {
            /** Format: uuid */
            camera_id: string;
            /** Format: date-time */
            start_time: string;
            /**
             * Format: date-time
             * @description At most 2 hours after start_time.
             */
            end_time: string;
            name?: string;
        };
        /** @enum {string} */
        ExportStatus: "pending" | "running" | "ready" | "failed";
        Export: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            site_id: string;
            /** Format: uuid */
            server_id: string;
            /** Format: uuid */
            camera_id: string;
            camera_name: string;
            /** Format: uuid */
            requested_by: string;
            requested_by_name: string;
            name: string;
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            status: components["schemas"]["ExportStatus"];
            /** @description 0 to 100. */
            progress: number;
            error: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: {
        /** @description The request is invalid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The caller lacks the permission on this resource */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist or belongs to another tenant */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request conflicts with existing data */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Frigate could not be reached or rejected the credentials */
        FrigateUnreachable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies are reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /** @description At least one dependency is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
    getSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPermissionCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["PermissionDefinition"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listGrants: {
        parameters: {
            query?: {
                subject_type?: components["schemas"]["SubjectType"];
                subject_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Grant"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGrant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTenants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Tenant"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listSites: {
        parameters: {
            query?: {
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Site"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                siteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Site */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                siteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                siteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SiteUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listServers: {
        parameters: {
            query?: {
                site_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Server"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerCreate"];
            };
        };
        responses: {
            /** @description Registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["FrigateUnreachable"];
        };
    };
    probeServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerProbe"];
            };
        };
        responses: {
            /** @description Connection works */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            502: components["responses"]["FrigateUnreachable"];
        };
    };
    getServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    syncServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Synchronised */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["FrigateUnreachable"];
        };
    };
    listCameras: {
        parameters: {
            query?: {
                site_id?: string;
                server_id?: string;
                group_id?: string;
                /** @description Case-insensitive name filter */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cameras */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Camera"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Camera */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Camera"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCameraGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Camera groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["CameraGroup"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCameraGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraGroupInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraGroup"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getCameraGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Camera group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraGroup"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceCameraGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraGroupInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraGroup"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteCameraGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                site_id?: string[];
                server_id?: string[];
                camera_id?: string[];
                label?: string[];
                zone?: string[];
                sub_label?: string[];
                severity?: components["schemas"]["Severity"];
                plate?: string;
                from?: string;
                to?: string;
                reviewed?: boolean;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listEventSyncStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per visible server */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["EventSyncStatus"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reviewed: boolean;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getEventThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["FrigateUnreachable"];
        };
    };
    listPlateReads: {
        parameters: {
            query?: {
                /** @description Plate or part of it; spaces and dashes are ignored. */
                plate?: string;
                exact?: boolean;
                site_id?: string[];
                camera_id?: string[];
                from?: string;
                to?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of plate reads */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlateReadPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in, or a TOTP code is needed */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Account temporarily locked */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    current_password: string;
                    /** Format: password */
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    setupMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secret to add to an authenticator app */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Base32 secret for manual entry. */
                        secret: string;
                        /** @description otpauth:// URL (render as QR). */
                        otpauth_url: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    enableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Enabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    disableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: password */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Disabled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["User"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listUserGroups: {
        parameters: {
            query?: {
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["UserGroup"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createUserGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserGroupInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getUserGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceUserGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserGroupInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGroup"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteUserGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                tenant_id?: string;
                action?: string;
                actor_id?: string;
                from?: string;
                to?: string;
                /** @description Return entries older than this id (pagination). */
                before_id?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entries, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEntry"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listViews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Views */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["View"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description View */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewInput"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCameraRecordings: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                cameraId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Spans, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["RecordingSpan"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["FrigateUnreachable"];
        };
    };
    listExports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exports, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Export"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportInput"];
            };
        };
        responses: {
            /** @description Started */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            502: components["responses"]["FrigateUnreachable"];
        };
    };
    getExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Export"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exportId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
